// Code generated by mockery v2.10.6. DO NOT EDIT.

package mock

import (
	exd "github.com/odpf/optimus/ext/exd"
	mock "github.com/stretchr/testify/mock"
)

// Installer is an autogenerated mock type for the Installer type
type Installer struct {
	mock.Mock
}

// Install provides a mock function with given fields: asset, remoteMetadata
func (_m *Installer) Install(asset []byte, remoteMetadata *exd.RemoteMetadata) error {
	ret := _m.Called(asset, remoteMetadata)

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte, *exd.RemoteMetadata) error); ok {
		r0 = rf(asset, remoteMetadata)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Prepare provides a mock function with given fields: remoteMetadata
func (_m *Installer) Prepare(remoteMetadata *exd.RemoteMetadata) error {
	ret := _m.Called(remoteMetadata)

	var r0 error
	if rf, ok := ret.Get(0).(func(*exd.RemoteMetadata) error); ok {
		r0 = rf(remoteMetadata)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
