// Code generated by mockery v2.10.6. DO NOT EDIT.

package mock

import (
	exd "github.com/odpf/optimus/ext/exd"
	mock "github.com/stretchr/testify/mock"
)

// Installer is an autogenerated mock type for the Installer type
type Installer struct {
	mock.Mock
}

// Install provides a mock function with given fields: _a0, _a1
func (_m *Installer) Install(_a0 []byte, _a1 *exd.Metadata) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte, *exd.Metadata) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Prepare provides a mock function with given fields: _a0
func (_m *Installer) Prepare(_a0 *exd.Metadata) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*exd.Metadata) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
