run:
  timeout: 5m
  skip-dirs:
    - api/proto
    - api/third_party
output:
  format: colored-line-number
linters:
  enable-all: true
  disable:
    # Rules to review
    - varnamelen
    - wrapcheck
    - tagliatelle
    - paralleltest
    - nlreturn
    - gochecknoglobals
    - exhaustivestruct
    - forcetypeassert
    - exhaustive
    - contextcheck
    - wsl
    - scopelint
    - promlinter
    - interfacer
    - gofumpt
    - godox
    - godot
    - gochecknoinits
    - gci
    - forbidigo
    - errcheck
    - maintidx
    - errchkjson

    # Following linters should be enabled after fixing the code
    - testpackage
    - cyclop
    - noctx
    - ireturn
    - goerr113
    - nilerr
    - errorlint
    - bodyclose
    - ifshort
    - prealloc
    - nestif
    - lll
    - maligned
    - nakedret
    - golint
    - gocritic
    - gocognit
    - funlen
    - gocyclo
    - dupl
linters-settings:
  revive:
    ignore-generated-header: true
    severity: warning
  goconst:
    ignore-tests: true
    numbers: true
  gomnd:
    ignored-numbers: # Why we have a big range of file permissions
      - '0600'
      - '0644'
      - '0655'
      - '0666'
      - '0770'
      - '0755'
      - '0765'
      - '0777'
    ignored-functions:
      - 'survey.MinLength'
      - 'survey.MaxLength'
      - 'args.Error'
  gosimple:
    go: "1.17"
    checks:
      - "all"
      - "-S1002"
severity:
  default-severity: error