run:
  timeout: 5m
  skip-dirs:
    - api/proto
    - api/third_party
output:
  format: colored-line-number
linters:
  enable-all: true
  disable:
    # Rules to review
    - varnamelen
    - wrapcheck
    - tagliatelle
    - paralleltest
    - nlreturn
    - gochecknoglobals
    - exhaustivestruct
    - forcetypeassert
    - exhaustive
    - contextcheck
    - wsl
    - scopelint
    - promlinter
    - interfacer
    - gosec
    - godox
    - godot
    - gci
    - forbidigo
    - errcheck
    - maintidx
    - errchkjson

    # Following linters should be enabled after fixing the code
    - testpackage
    - cyclop
    - noctx
    - ireturn
    - goerr113
    - nilerr
    - bodyclose
    - prealloc
    - nestif
    - lll
    - maligned
    - golint
    - gocognit
    - funlen
    - gocyclo
    - dupl
linters-settings:
  gofumpt:
    lang-version: "1.17"
    extra-rules: true
  revive:
    ignore-generated-header: true
    severity: warning
  goconst:
    ignore-tests: true
    numbers: true
  gomnd:
    ignored-numbers: # Why we have a big range of file permissions
      - '0o644'
      - '0o655'
      - '0o666'
      - '0o770'
      - '0o755'
      - '0o765'
      - '0o777'
    ignored-functions:
      - 'survey.MinLength'
      - 'survey.MaxLength'
      - 'args.Error'
  gosimple:
    go: "1.17"
    checks:
      - "all"
      - "-S1002"
  gocritic:
    disabled-checks:
      - ifElseChain
      - singleCaseSwitch
    enabled-tags:
      - diagnostic
#      - style
#      - opinionated
#      - performance
  unparam:
    # Inspect exported functions.
    # XXX: if you enable this setting, unparam will report a lot of false-positives in text editors:
    check-exported: true
issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocritic
severity:
  default-severity: error