output:
  format: line-number
linters:
  enable-all: false
  disable-all: true
  enable:
    - vet
    - goimports
    - thelper
    - tparallel
    - unconvert
    - wastedassign
    - revive
    - unused
    - gofmt
    - whitespace
    - misspell
linters-settings:
  revive:
    ignore-generated-header: true
    severity: warning
  gofmt:
    simplify: false
severity:
  default-severity: error