project_name: optimus

before:
  hooks:
    - make install
builds:
  - main: ./main.go
    id: "optimus"
    binary: optimus
    flags:
      - -a
    ldflags:
      - -s -w -X github.com/raystack/optimus/config.BuildVersion={{ .Version }} -X github.com/raystack/optimus/config.BuildCommit={{.FullCommit}} -X github.com/raystack/optimus/config.BuildDate={{.Date}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
archives:
  - replacements:
      darwin: macos
      linux: linux
      windows: windows
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
release:
  prerelease: auto
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs"
      - "^test"
      - "^build"
      - "^chore"
dockers:
  - goos: linux
    goarch: amd64
    ids:
      - optimus
    dockerfile: Dockerfile
    image_templates:
      - "docker.io/raystack/{{.ProjectName}}:{{ .Version }}"
      - "docker.io/raystack/{{.ProjectName}}:{{ .Version }}-amd64"
    extra_files:
      - entrypoint_init_container.sh
brews:
  - name: optimus
    tap:
      owner: raystack
      name: homebrew-tap
    license: "Apache 2.0"
    description: "Optimus helps your organization to build & manage data pipelines with ease."
    homepage: https://raystack.github.io/optimus
    folder: Formula
    skip_upload: auto
    dependencies:
      - name: git
    install: |-
      bin.install "optimus"
    commit_author:
      name: Ravi Suhag
      email: suhag.ravi@gmail.com
