version: 1

# logging configuration
log:
  # debug, info, warning, error, fatal - default 'info'
  level: info

#
# cli configurations
#

# used to connect optimus service
#host: localhost:9100

# for configuring optimus project
#project:
#  name: sample_project
#  # project variables usable in specifications
#  config:
#    environment: integration
#    scheduler_host: http://example.io/
#    # storage_path is used for storing compiled job specifications that can be
#    # consumed by schedulers like Airflow
#    # it supports multiple schemes like: file://, gcs://
#    storage_path: file://absolute_path_to_a_directory

# for configuring optimus namespace
#namespace:
#  name: sample_namespace
#  job:
#    # folder where job specifications are stored
#    path: "job"
#  datastore:
#    # optimus is capable of supporting multiple datastores
#    type: bigquery
#    # path where resource spec for BQ are stored
#    path: "bq"
#  # namespace variables usable in specifications
#  config: {}

#
# server configurations
#

# for configuring optimus service
#serve:
#  # port to listen on
#  port: 9100
#
#  # host to listen on
#  host: localhost
#
#  # this gets injected in compiled dags to reach back out to optimus service
#  # when they run
#  ingress_host: optimus.example.io:80
#
#  # 32 char hash used for encrypting secrets
#  # note: use a different one in production please
#  app_key: Yjo4a0jn1NvYdq79SADC/KaVv9Wu0Ffc
#
#  # database configurations
#  db:
#    # database connection string
#    dsn: postgres://user:password@localhost:5432/database?sslmode=disable
#
#    max_idle_connection: 5
#    max_open_connection: 10

# optimus supports multiple scheduler types
#scheduler:
#  # name of the registered scheduler, default: airflow2
#  name: airflow2
#  # skip bootstrap step of scheduler required for proper functioning
#  # but can be disabled for local development, default: false
#  skip_init: true

# application telemetry
#telemetry:
#
#  # configure the host:port used for
#  # - exposing profiling metrics via pprof over /debug
#  # - prometheus stats over /metrics
#  profile_addr: ":9110"
#
#  # jaeger collector address to send application traces
#  jaeger_addr: "http://localhost:14268/api/traces"