app:
  labels:
    environment: dev

image:
  repository: odpf/optimus
  tag: "0.4.1"
  pullPolicy: IfNotPresent

container:
  command:
    - optimus
  args:
    - serve
    - --install-plugins
    - -c
    - /etc/optimus/config.yaml  # mounted as per helm chart
  volumeMounts:
    - mountPath: /airflow-dags/dags
      name: dags-path
    - mountPath: /app/.plugins
      name: plugins-path
    - mountPath: /app/optimus-dummy-plugins.tar.gz # will be replace from makefile
      name: plugins-artifact

volumes:
  - name: dags-path
    hostPath: 
      path: /tmp/colima/dags
      type: Directory
  - name: plugins-path
    hostPath: 
      path: /tmp/colima/plugins
      type: Directory
  - name: plugins-artifact
    hostPath: 
      path: /tmp/colima/optimus-dummy-plugins.tar.gz # will be replaced from makefile
      type: File

telegraf:
  enabled: false
ingress:
  enabled: false

configYaml: |-
  version: 1
  log:
    level: DEBUG
  serve:
    ingress_host: optimus.optimus.svc.cluster.local
  scheduler:
    name: airflow2

config:
  OPTIMUS_SERVE_DB_DSN: postgres://optimus:optimus@database-service/optimus?sslmode=disable
  OPTIMUS_SERVE_APP_KEY: TuMxWWp4NkqNqaes6vK9DeqgUkk8I97s
