DELETE FROM JOB_RUN
WHERE (JOB_NAME, SCHEDULED_AT) IN (
    SELECT JOB_NAME, SCHEDULED_AT
    FROM JOB_RUN
    GROUP BY JOB_NAME, SCHEDULED_AT
    HAVING COUNT(*) > 1
);

ALTER TABLE JOB_RUN
ADD CONSTRAINT pk_constraint_job_name_scheduled_at UNIQUE (JOB_NAME, SCHEDULED_AT);