CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE TABLE IF NOT EXISTS backup (
  id UUID PRIMARY KEY NOT NULL,
  resource_id UUID NOT NULL REFERENCES resource (id) ON DELETE CASCADE,
  spec JSONB,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
