// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: odpf/optimus/hook_plugin.proto

package optimus

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GetHookSchema struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetHookSchema) Reset() {
	*x = GetHookSchema{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_hook_plugin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHookSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHookSchema) ProtoMessage() {}

func (x *GetHookSchema) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_hook_plugin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHookSchema.ProtoReflect.Descriptor instead.
func (*GetHookSchema) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_hook_plugin_proto_rawDescGZIP(), []int{0}
}

type GetHookQuestions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetHookQuestions) Reset() {
	*x = GetHookQuestions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_hook_plugin_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHookQuestions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHookQuestions) ProtoMessage() {}

func (x *GetHookQuestions) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_hook_plugin_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHookQuestions.ProtoReflect.Descriptor instead.
func (*GetHookQuestions) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_hook_plugin_proto_rawDescGZIP(), []int{1}
}

type ValidateHookQuestion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ValidateHookQuestion) Reset() {
	*x = ValidateHookQuestion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_hook_plugin_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateHookQuestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateHookQuestion) ProtoMessage() {}

func (x *ValidateHookQuestion) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_hook_plugin_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateHookQuestion.ProtoReflect.Descriptor instead.
func (*ValidateHookQuestion) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_hook_plugin_proto_rawDescGZIP(), []int{2}
}

type HookConfigs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Configs []*HookConfigs_Config `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty"`
}

func (x *HookConfigs) Reset() {
	*x = HookConfigs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_hook_plugin_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HookConfigs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookConfigs) ProtoMessage() {}

func (x *HookConfigs) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_hook_plugin_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookConfigs.ProtoReflect.Descriptor instead.
func (*HookConfigs) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_hook_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *HookConfigs) GetConfigs() []*HookConfigs_Config {
	if x != nil {
		return x.Configs
	}
	return nil
}

type DefaultHookConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DefaultHookConfig) Reset() {
	*x = DefaultHookConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_hook_plugin_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DefaultHookConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultHookConfig) ProtoMessage() {}

func (x *DefaultHookConfig) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_hook_plugin_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultHookConfig.ProtoReflect.Descriptor instead.
func (*DefaultHookConfig) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_hook_plugin_proto_rawDescGZIP(), []int{4}
}

type HookAssets struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Assets []*HookAssets_Asset `protobuf:"bytes,1,rep,name=assets,proto3" json:"assets,omitempty"`
}

func (x *HookAssets) Reset() {
	*x = HookAssets{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_hook_plugin_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HookAssets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookAssets) ProtoMessage() {}

func (x *HookAssets) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_hook_plugin_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookAssets.ProtoReflect.Descriptor instead.
func (*HookAssets) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_hook_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *HookAssets) GetAssets() []*HookAssets_Asset {
	if x != nil {
		return x.Assets
	}
	return nil
}

type DefaultHookAssets struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DefaultHookAssets) Reset() {
	*x = DefaultHookAssets{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_hook_plugin_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DefaultHookAssets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultHookAssets) ProtoMessage() {}

func (x *DefaultHookAssets) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_hook_plugin_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultHookAssets.ProtoReflect.Descriptor instead.
func (*DefaultHookAssets) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_hook_plugin_proto_rawDescGZIP(), []int{6}
}

type GetHookSchema_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetHookSchema_Request) Reset() {
	*x = GetHookSchema_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_hook_plugin_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHookSchema_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHookSchema_Request) ProtoMessage() {}

func (x *GetHookSchema_Request) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_hook_plugin_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHookSchema_Request.ProtoReflect.Descriptor instead.
func (*GetHookSchema_Request) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_hook_plugin_proto_rawDescGZIP(), []int{0, 0}
}

type GetHookSchema_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Image       string   `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Type        string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	DependsOn   []string `protobuf:"bytes,5,rep,name=depends_on,json=dependsOn,proto3" json:"depends_on,omitempty"`
	// will be mounted inside the container as volume
	SecretPath string `protobuf:"bytes,6,opt,name=secret_path,json=secretPath,proto3" json:"secret_path,omitempty"`
}

func (x *GetHookSchema_Response) Reset() {
	*x = GetHookSchema_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_hook_plugin_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHookSchema_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHookSchema_Response) ProtoMessage() {}

func (x *GetHookSchema_Response) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_hook_plugin_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHookSchema_Response.ProtoReflect.Descriptor instead.
func (*GetHookSchema_Response) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_hook_plugin_proto_rawDescGZIP(), []int{0, 1}
}

func (x *GetHookSchema_Response) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetHookSchema_Response) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetHookSchema_Response) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *GetHookSchema_Response) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetHookSchema_Response) GetDependsOn() []string {
	if x != nil {
		return x.DependsOn
	}
	return nil
}

func (x *GetHookSchema_Response) GetSecretPath() string {
	if x != nil {
		return x.SecretPath
	}
	return ""
}

type GetHookQuestions_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Options *PluginOptions `protobuf:"bytes,40,opt,name=options,proto3" json:"options,omitempty"`
}

func (x *GetHookQuestions_Request) Reset() {
	*x = GetHookQuestions_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_hook_plugin_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHookQuestions_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHookQuestions_Request) ProtoMessage() {}

func (x *GetHookQuestions_Request) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_hook_plugin_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHookQuestions_Request.ProtoReflect.Descriptor instead.
func (*GetHookQuestions_Request) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_hook_plugin_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetHookQuestions_Request) GetOptions() *PluginOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type GetHookQuestions_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Questions []*PluginQuestion `protobuf:"bytes,1,rep,name=questions,proto3" json:"questions,omitempty"`
}

func (x *GetHookQuestions_Response) Reset() {
	*x = GetHookQuestions_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_hook_plugin_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHookQuestions_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHookQuestions_Response) ProtoMessage() {}

func (x *GetHookQuestions_Response) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_hook_plugin_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHookQuestions_Response.ProtoReflect.Descriptor instead.
func (*GetHookQuestions_Response) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_hook_plugin_proto_rawDescGZIP(), []int{1, 1}
}

func (x *GetHookQuestions_Response) GetQuestions() []*PluginQuestion {
	if x != nil {
		return x.Questions
	}
	return nil
}

type ValidateHookQuestion_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Answer  *PluginAnswer  `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	Options *PluginOptions `protobuf:"bytes,40,opt,name=options,proto3" json:"options,omitempty"`
}

func (x *ValidateHookQuestion_Request) Reset() {
	*x = ValidateHookQuestion_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_hook_plugin_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateHookQuestion_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateHookQuestion_Request) ProtoMessage() {}

func (x *ValidateHookQuestion_Request) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_hook_plugin_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateHookQuestion_Request.ProtoReflect.Descriptor instead.
func (*ValidateHookQuestion_Request) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_hook_plugin_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ValidateHookQuestion_Request) GetAnswer() *PluginAnswer {
	if x != nil {
		return x.Answer
	}
	return nil
}

func (x *ValidateHookQuestion_Request) GetOptions() *PluginOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type ValidateHookQuestion_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ValidateHookQuestion_Response) Reset() {
	*x = ValidateHookQuestion_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_hook_plugin_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateHookQuestion_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateHookQuestion_Response) ProtoMessage() {}

func (x *ValidateHookQuestion_Response) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_hook_plugin_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateHookQuestion_Response.ProtoReflect.Descriptor instead.
func (*ValidateHookQuestion_Response) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_hook_plugin_proto_rawDescGZIP(), []int{2, 1}
}

func (x *ValidateHookQuestion_Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ValidateHookQuestion_Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type HookConfigs_Config struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *HookConfigs_Config) Reset() {
	*x = HookConfigs_Config{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_hook_plugin_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HookConfigs_Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookConfigs_Config) ProtoMessage() {}

func (x *HookConfigs_Config) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_hook_plugin_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookConfigs_Config.ProtoReflect.Descriptor instead.
func (*HookConfigs_Config) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_hook_plugin_proto_rawDescGZIP(), []int{3, 0}
}

func (x *HookConfigs_Config) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HookConfigs_Config) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type DefaultHookConfig_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Answers     []*PluginAnswer `protobuf:"bytes,1,rep,name=answers,proto3" json:"answers,omitempty"`
	TaskConfigs *TaskConfigs    `protobuf:"bytes,2,opt,name=task_configs,json=taskConfigs,proto3" json:"task_configs,omitempty"`
	Options     *PluginOptions  `protobuf:"bytes,40,opt,name=options,proto3" json:"options,omitempty"`
}

func (x *DefaultHookConfig_Request) Reset() {
	*x = DefaultHookConfig_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_hook_plugin_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DefaultHookConfig_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultHookConfig_Request) ProtoMessage() {}

func (x *DefaultHookConfig_Request) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_hook_plugin_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultHookConfig_Request.ProtoReflect.Descriptor instead.
func (*DefaultHookConfig_Request) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_hook_plugin_proto_rawDescGZIP(), []int{4, 0}
}

func (x *DefaultHookConfig_Request) GetAnswers() []*PluginAnswer {
	if x != nil {
		return x.Answers
	}
	return nil
}

func (x *DefaultHookConfig_Request) GetTaskConfigs() *TaskConfigs {
	if x != nil {
		return x.TaskConfigs
	}
	return nil
}

func (x *DefaultHookConfig_Request) GetOptions() *PluginOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type DefaultHookConfig_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config *HookConfigs `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *DefaultHookConfig_Response) Reset() {
	*x = DefaultHookConfig_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_hook_plugin_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DefaultHookConfig_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultHookConfig_Response) ProtoMessage() {}

func (x *DefaultHookConfig_Response) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_hook_plugin_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultHookConfig_Response.ProtoReflect.Descriptor instead.
func (*DefaultHookConfig_Response) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_hook_plugin_proto_rawDescGZIP(), []int{4, 1}
}

func (x *DefaultHookConfig_Response) GetConfig() *HookConfigs {
	if x != nil {
		return x.Config
	}
	return nil
}

type HookAssets_Asset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *HookAssets_Asset) Reset() {
	*x = HookAssets_Asset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_hook_plugin_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HookAssets_Asset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookAssets_Asset) ProtoMessage() {}

func (x *HookAssets_Asset) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_hook_plugin_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookAssets_Asset.ProtoReflect.Descriptor instead.
func (*HookAssets_Asset) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_hook_plugin_proto_rawDescGZIP(), []int{5, 0}
}

func (x *HookAssets_Asset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HookAssets_Asset) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type DefaultHookAssets_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Answers     []*PluginAnswer `protobuf:"bytes,1,rep,name=answers,proto3" json:"answers,omitempty"`
	TaskConfigs *TaskConfigs    `protobuf:"bytes,2,opt,name=task_configs,json=taskConfigs,proto3" json:"task_configs,omitempty"`
	Options     *PluginOptions  `protobuf:"bytes,40,opt,name=options,proto3" json:"options,omitempty"`
}

func (x *DefaultHookAssets_Request) Reset() {
	*x = DefaultHookAssets_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_hook_plugin_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DefaultHookAssets_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultHookAssets_Request) ProtoMessage() {}

func (x *DefaultHookAssets_Request) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_hook_plugin_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultHookAssets_Request.ProtoReflect.Descriptor instead.
func (*DefaultHookAssets_Request) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_hook_plugin_proto_rawDescGZIP(), []int{6, 0}
}

func (x *DefaultHookAssets_Request) GetAnswers() []*PluginAnswer {
	if x != nil {
		return x.Answers
	}
	return nil
}

func (x *DefaultHookAssets_Request) GetTaskConfigs() *TaskConfigs {
	if x != nil {
		return x.TaskConfigs
	}
	return nil
}

func (x *DefaultHookAssets_Request) GetOptions() *PluginOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type DefaultHookAssets_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Assets *HookAssets `protobuf:"bytes,1,opt,name=assets,proto3" json:"assets,omitempty"`
}

func (x *DefaultHookAssets_Response) Reset() {
	*x = DefaultHookAssets_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_hook_plugin_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DefaultHookAssets_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultHookAssets_Response) ProtoMessage() {}

func (x *DefaultHookAssets_Response) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_hook_plugin_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultHookAssets_Response.ProtoReflect.Descriptor instead.
func (*DefaultHookAssets_Response) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_hook_plugin_proto_rawDescGZIP(), []int{6, 1}
}

func (x *DefaultHookAssets_Response) GetAssets() *HookAssets {
	if x != nil {
		return x.Assets
	}
	return nil
}

var File_odpf_optimus_hook_plugin_proto protoreflect.FileDescriptor

var file_odpf_optimus_hook_plugin_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x6f, 0x64, 0x70, 0x66, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2f, 0x68,
	0x6f, 0x6f, 0x6b, 0x5f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0c, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x1a, 0x1e,
	0x6f, 0x64, 0x70, 0x66, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2f, 0x74, 0x61, 0x73,
	0x6b, 0x5f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc7,
	0x01, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x6f, 0x6b, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61,
	0x1a, 0x09, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0xaa, 0x01, 0x0a, 0x08,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14,
	0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x65, 0x70, 0x65,
	0x6e, 0x64, 0x73, 0x5f, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x64, 0x65,
	0x70, 0x65, 0x6e, 0x64, 0x73, 0x4f, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65,
	0x63, 0x72, 0x65, 0x74, 0x50, 0x61, 0x74, 0x68, 0x22, 0x9c, 0x01, 0x0a, 0x10, 0x47, 0x65, 0x74,
	0x48, 0x6f, 0x6f, 0x6b, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x40, 0x0a,
	0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0x28, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6f, 0x64, 0x70, 0x66,
	0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a,
	0x46, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x09, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x50, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0xc8, 0x01, 0x0a, 0x14, 0x56, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x6f, 0x6b, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e,
	0x1a, 0x74, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x32, 0x0a, 0x06, 0x61,
	0x6e, 0x73, 0x77, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6f, 0x64,
	0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12,
	0x35, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x28, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e,
	0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x07, 0x6f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x3a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x22, 0x7d, 0x0a, 0x0b, 0x48, 0x6f, 0x6f, 0x6b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x73, 0x12, 0x3a, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75,
	0x73, 0x2e, 0x48, 0x6f, 0x6f, 0x6b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x2e, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x1a, 0x32, 0x0a,
	0x06, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0x89, 0x02, 0x0a, 0x11, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x48, 0x6f, 0x6f,
	0x6b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x1a, 0xb4, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x34, 0x0a, 0x07, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69,
	0x6d, 0x75, 0x73, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72,
	0x52, 0x07, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x12, 0x3c, 0x0a, 0x0c, 0x74, 0x61, 0x73,
	0x6b, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x54,
	0x61, 0x73, 0x6b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x52, 0x0b, 0x74, 0x61, 0x73, 0x6b,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x12, 0x35, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0x28, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e,
	0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x3d,
	0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x06, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6f, 0x64, 0x70,
	0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x48, 0x6f, 0x6f, 0x6b, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x73, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x77, 0x0a,
	0x0a, 0x48, 0x6f, 0x6f, 0x6b, 0x41, 0x73, 0x73, 0x65, 0x74, 0x73, 0x12, 0x36, 0x0a, 0x06, 0x61,
	0x73, 0x73, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6f, 0x64,
	0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x48, 0x6f, 0x6f, 0x6b, 0x41,
	0x73, 0x73, 0x65, 0x74, 0x73, 0x2e, 0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x06, 0x61, 0x73, 0x73,
	0x65, 0x74, 0x73, 0x1a, 0x31, 0x0a, 0x05, 0x41, 0x73, 0x73, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x88, 0x02, 0x0a, 0x11, 0x44, 0x65, 0x66, 0x61, 0x75,
	0x6c, 0x74, 0x48, 0x6f, 0x6f, 0x6b, 0x41, 0x73, 0x73, 0x65, 0x74, 0x73, 0x1a, 0xb4, 0x01, 0x0a,
	0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x34, 0x0a, 0x07, 0x61, 0x6e, 0x73, 0x77,
	0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6f, 0x64, 0x70, 0x66,
	0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x41,
	0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x07, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x12, 0x3c,
	0x0a, 0x0c, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69,
	0x6d, 0x75, 0x73, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x52,
	0x0b, 0x74, 0x61, 0x73, 0x6b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x12, 0x35, 0x0a, 0x07,
	0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x28, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x50, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x1a, 0x3c, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x30, 0x0a, 0x06, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x48,
	0x6f, 0x6f, 0x6b, 0x41, 0x73, 0x73, 0x65, 0x74, 0x73, 0x52, 0x06, 0x61, 0x73, 0x73, 0x65, 0x74,
	0x73, 0x32, 0x8e, 0x04, 0x0a, 0x0a, 0x48, 0x6f, 0x6f, 0x6b, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x12, 0x5a, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x6f, 0x6b, 0x53, 0x63, 0x68, 0x65, 0x6d,
	0x61, 0x12, 0x23, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73,
	0x2e, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x6f, 0x6b, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70,
	0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x6f, 0x6b, 0x53, 0x63, 0x68,
	0x65, 0x6d, 0x61, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x63, 0x0a, 0x10,
	0x47, 0x65, 0x74, 0x48, 0x6f, 0x6f, 0x6b, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x12, 0x26, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e,
	0x47, 0x65, 0x74, 0x48, 0x6f, 0x6f, 0x6b, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e,
	0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x6f, 0x6b, 0x51,
	0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x6f, 0x0a, 0x14, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x6f,
	0x6b, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2a, 0x2e, 0x6f, 0x64, 0x70, 0x66,
	0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x48, 0x6f, 0x6f, 0x6b, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74,
	0x69, 0x6d, 0x75, 0x73, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x6f,
	0x6b, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x66, 0x0a, 0x11, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x48, 0x6f, 0x6f,
	0x6b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x27, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f,
	0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x48, 0x6f,
	0x6f, 0x6b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x28, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e,
	0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x48, 0x6f, 0x6f, 0x6b, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x66, 0x0a, 0x11, 0x44, 0x65,
	0x66, 0x61, 0x75, 0x6c, 0x74, 0x48, 0x6f, 0x6f, 0x6b, 0x41, 0x73, 0x73, 0x65, 0x74, 0x73, 0x12,
	0x27, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x44,
	0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x48, 0x6f, 0x6f, 0x6b, 0x41, 0x73, 0x73, 0x65, 0x74, 0x73,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e,
	0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x48,
	0x6f, 0x6f, 0x6b, 0x41, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x4d, 0x0a, 0x16, 0x69, 0x6f, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x6e, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x42, 0x11, 0x48, 0x6f,
	0x6f, 0x6b, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x50,
	0x01, 0x5a, 0x1e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x64,
	0x70, 0x66, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6e, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_odpf_optimus_hook_plugin_proto_rawDescOnce sync.Once
	file_odpf_optimus_hook_plugin_proto_rawDescData = file_odpf_optimus_hook_plugin_proto_rawDesc
)

func file_odpf_optimus_hook_plugin_proto_rawDescGZIP() []byte {
	file_odpf_optimus_hook_plugin_proto_rawDescOnce.Do(func() {
		file_odpf_optimus_hook_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(file_odpf_optimus_hook_plugin_proto_rawDescData)
	})
	return file_odpf_optimus_hook_plugin_proto_rawDescData
}

var file_odpf_optimus_hook_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_odpf_optimus_hook_plugin_proto_goTypes = []interface{}{
	(*GetHookSchema)(nil),                 // 0: odpf.optimus.GetHookSchema
	(*GetHookQuestions)(nil),              // 1: odpf.optimus.GetHookQuestions
	(*ValidateHookQuestion)(nil),          // 2: odpf.optimus.ValidateHookQuestion
	(*HookConfigs)(nil),                   // 3: odpf.optimus.HookConfigs
	(*DefaultHookConfig)(nil),             // 4: odpf.optimus.DefaultHookConfig
	(*HookAssets)(nil),                    // 5: odpf.optimus.HookAssets
	(*DefaultHookAssets)(nil),             // 6: odpf.optimus.DefaultHookAssets
	(*GetHookSchema_Request)(nil),         // 7: odpf.optimus.GetHookSchema.Request
	(*GetHookSchema_Response)(nil),        // 8: odpf.optimus.GetHookSchema.Response
	(*GetHookQuestions_Request)(nil),      // 9: odpf.optimus.GetHookQuestions.Request
	(*GetHookQuestions_Response)(nil),     // 10: odpf.optimus.GetHookQuestions.Response
	(*ValidateHookQuestion_Request)(nil),  // 11: odpf.optimus.ValidateHookQuestion.Request
	(*ValidateHookQuestion_Response)(nil), // 12: odpf.optimus.ValidateHookQuestion.Response
	(*HookConfigs_Config)(nil),            // 13: odpf.optimus.HookConfigs.Config
	(*DefaultHookConfig_Request)(nil),     // 14: odpf.optimus.DefaultHookConfig.Request
	(*DefaultHookConfig_Response)(nil),    // 15: odpf.optimus.DefaultHookConfig.Response
	(*HookAssets_Asset)(nil),              // 16: odpf.optimus.HookAssets.Asset
	(*DefaultHookAssets_Request)(nil),     // 17: odpf.optimus.DefaultHookAssets.Request
	(*DefaultHookAssets_Response)(nil),    // 18: odpf.optimus.DefaultHookAssets.Response
	(*PluginOptions)(nil),                 // 19: odpf.optimus.PluginOptions
	(*PluginQuestion)(nil),                // 20: odpf.optimus.PluginQuestion
	(*PluginAnswer)(nil),                  // 21: odpf.optimus.PluginAnswer
	(*TaskConfigs)(nil),                   // 22: odpf.optimus.TaskConfigs
}
var file_odpf_optimus_hook_plugin_proto_depIdxs = []int32{
	13, // 0: odpf.optimus.HookConfigs.configs:type_name -> odpf.optimus.HookConfigs.Config
	16, // 1: odpf.optimus.HookAssets.assets:type_name -> odpf.optimus.HookAssets.Asset
	19, // 2: odpf.optimus.GetHookQuestions.Request.options:type_name -> odpf.optimus.PluginOptions
	20, // 3: odpf.optimus.GetHookQuestions.Response.questions:type_name -> odpf.optimus.PluginQuestion
	21, // 4: odpf.optimus.ValidateHookQuestion.Request.answer:type_name -> odpf.optimus.PluginAnswer
	19, // 5: odpf.optimus.ValidateHookQuestion.Request.options:type_name -> odpf.optimus.PluginOptions
	21, // 6: odpf.optimus.DefaultHookConfig.Request.answers:type_name -> odpf.optimus.PluginAnswer
	22, // 7: odpf.optimus.DefaultHookConfig.Request.task_configs:type_name -> odpf.optimus.TaskConfigs
	19, // 8: odpf.optimus.DefaultHookConfig.Request.options:type_name -> odpf.optimus.PluginOptions
	3,  // 9: odpf.optimus.DefaultHookConfig.Response.config:type_name -> odpf.optimus.HookConfigs
	21, // 10: odpf.optimus.DefaultHookAssets.Request.answers:type_name -> odpf.optimus.PluginAnswer
	22, // 11: odpf.optimus.DefaultHookAssets.Request.task_configs:type_name -> odpf.optimus.TaskConfigs
	19, // 12: odpf.optimus.DefaultHookAssets.Request.options:type_name -> odpf.optimus.PluginOptions
	5,  // 13: odpf.optimus.DefaultHookAssets.Response.assets:type_name -> odpf.optimus.HookAssets
	7,  // 14: odpf.optimus.HookPlugin.GetHookSchema:input_type -> odpf.optimus.GetHookSchema.Request
	9,  // 15: odpf.optimus.HookPlugin.GetHookQuestions:input_type -> odpf.optimus.GetHookQuestions.Request
	11, // 16: odpf.optimus.HookPlugin.ValidateHookQuestion:input_type -> odpf.optimus.ValidateHookQuestion.Request
	14, // 17: odpf.optimus.HookPlugin.DefaultHookConfig:input_type -> odpf.optimus.DefaultHookConfig.Request
	17, // 18: odpf.optimus.HookPlugin.DefaultHookAssets:input_type -> odpf.optimus.DefaultHookAssets.Request
	8,  // 19: odpf.optimus.HookPlugin.GetHookSchema:output_type -> odpf.optimus.GetHookSchema.Response
	10, // 20: odpf.optimus.HookPlugin.GetHookQuestions:output_type -> odpf.optimus.GetHookQuestions.Response
	12, // 21: odpf.optimus.HookPlugin.ValidateHookQuestion:output_type -> odpf.optimus.ValidateHookQuestion.Response
	15, // 22: odpf.optimus.HookPlugin.DefaultHookConfig:output_type -> odpf.optimus.DefaultHookConfig.Response
	18, // 23: odpf.optimus.HookPlugin.DefaultHookAssets:output_type -> odpf.optimus.DefaultHookAssets.Response
	19, // [19:24] is the sub-list for method output_type
	14, // [14:19] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_odpf_optimus_hook_plugin_proto_init() }
func file_odpf_optimus_hook_plugin_proto_init() {
	if File_odpf_optimus_hook_plugin_proto != nil {
		return
	}
	file_odpf_optimus_task_plugin_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_odpf_optimus_hook_plugin_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHookSchema); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_hook_plugin_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHookQuestions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_hook_plugin_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidateHookQuestion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_hook_plugin_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HookConfigs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_hook_plugin_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DefaultHookConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_hook_plugin_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HookAssets); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_hook_plugin_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DefaultHookAssets); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_hook_plugin_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHookSchema_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_hook_plugin_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHookSchema_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_hook_plugin_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHookQuestions_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_hook_plugin_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHookQuestions_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_hook_plugin_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidateHookQuestion_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_hook_plugin_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidateHookQuestion_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_hook_plugin_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HookConfigs_Config); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_hook_plugin_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DefaultHookConfig_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_hook_plugin_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DefaultHookConfig_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_hook_plugin_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HookAssets_Asset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_hook_plugin_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DefaultHookAssets_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_hook_plugin_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DefaultHookAssets_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_odpf_optimus_hook_plugin_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_odpf_optimus_hook_plugin_proto_goTypes,
		DependencyIndexes: file_odpf_optimus_hook_plugin_proto_depIdxs,
		MessageInfos:      file_odpf_optimus_hook_plugin_proto_msgTypes,
	}.Build()
	File_odpf_optimus_hook_plugin_proto = out.File
	file_odpf_optimus_hook_plugin_proto_rawDesc = nil
	file_odpf_optimus_hook_plugin_proto_goTypes = nil
	file_odpf_optimus_hook_plugin_proto_depIdxs = nil
}
