// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.17.1
// source: odpf/optimus/task_plugin.proto

package optimus

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type PluginOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DryRun bool `protobuf:"varint,1,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
}

func (x *PluginOptions) Reset() {
	*x = PluginOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_task_plugin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PluginOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginOptions) ProtoMessage() {}

func (x *PluginOptions) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_task_plugin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginOptions.ProtoReflect.Descriptor instead.
func (*PluginOptions) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_task_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *PluginOptions) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

type GetTaskSchema struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetTaskSchema) Reset() {
	*x = GetTaskSchema{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_task_plugin_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTaskSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskSchema) ProtoMessage() {}

func (x *GetTaskSchema) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_task_plugin_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskSchema.ProtoReflect.Descriptor instead.
func (*GetTaskSchema) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_task_plugin_proto_rawDescGZIP(), []int{1}
}

type PluginQuestion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name                string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Prompt              string            `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Help                string            `protobuf:"bytes,3,opt,name=help,proto3" json:"help,omitempty"`
	Default             string            `protobuf:"bytes,4,opt,name=default,proto3" json:"default,omitempty"`
	Multiselect         []string          `protobuf:"bytes,5,rep,name=multiselect,proto3" json:"multiselect,omitempty"`
	SubQuestionsIfValue string            `protobuf:"bytes,6,opt,name=sub_questions_if_value,json=subQuestionsIfValue,proto3" json:"sub_questions_if_value,omitempty"`
	SubQuestions        []*PluginQuestion `protobuf:"bytes,7,rep,name=sub_questions,json=subQuestions,proto3" json:"sub_questions,omitempty"`
}

func (x *PluginQuestion) Reset() {
	*x = PluginQuestion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_task_plugin_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PluginQuestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginQuestion) ProtoMessage() {}

func (x *PluginQuestion) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_task_plugin_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginQuestion.ProtoReflect.Descriptor instead.
func (*PluginQuestion) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_task_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *PluginQuestion) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginQuestion) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *PluginQuestion) GetHelp() string {
	if x != nil {
		return x.Help
	}
	return ""
}

func (x *PluginQuestion) GetDefault() string {
	if x != nil {
		return x.Default
	}
	return ""
}

func (x *PluginQuestion) GetMultiselect() []string {
	if x != nil {
		return x.Multiselect
	}
	return nil
}

func (x *PluginQuestion) GetSubQuestionsIfValue() string {
	if x != nil {
		return x.SubQuestionsIfValue
	}
	return ""
}

func (x *PluginQuestion) GetSubQuestions() []*PluginQuestion {
	if x != nil {
		return x.SubQuestions
	}
	return nil
}

type PluginAnswer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Question *PluginQuestion `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	Value    string          `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *PluginAnswer) Reset() {
	*x = PluginAnswer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_task_plugin_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PluginAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginAnswer) ProtoMessage() {}

func (x *PluginAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_task_plugin_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginAnswer.ProtoReflect.Descriptor instead.
func (*PluginAnswer) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_task_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *PluginAnswer) GetQuestion() *PluginQuestion {
	if x != nil {
		return x.Question
	}
	return nil
}

func (x *PluginAnswer) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GetTaskQuestions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetTaskQuestions) Reset() {
	*x = GetTaskQuestions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_task_plugin_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTaskQuestions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskQuestions) ProtoMessage() {}

func (x *GetTaskQuestions) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_task_plugin_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskQuestions.ProtoReflect.Descriptor instead.
func (*GetTaskQuestions) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_task_plugin_proto_rawDescGZIP(), []int{4}
}

type ValidateTaskQuestion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ValidateTaskQuestion) Reset() {
	*x = ValidateTaskQuestion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_task_plugin_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateTaskQuestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTaskQuestion) ProtoMessage() {}

func (x *ValidateTaskQuestion) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_task_plugin_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTaskQuestion.ProtoReflect.Descriptor instead.
func (*ValidateTaskQuestion) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_task_plugin_proto_rawDescGZIP(), []int{5}
}

type TaskConfigs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Configs []*TaskConfigs_Config `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty"`
}

func (x *TaskConfigs) Reset() {
	*x = TaskConfigs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_task_plugin_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskConfigs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskConfigs) ProtoMessage() {}

func (x *TaskConfigs) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_task_plugin_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskConfigs.ProtoReflect.Descriptor instead.
func (*TaskConfigs) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_task_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *TaskConfigs) GetConfigs() []*TaskConfigs_Config {
	if x != nil {
		return x.Configs
	}
	return nil
}

type DefaultTaskConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DefaultTaskConfig) Reset() {
	*x = DefaultTaskConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_task_plugin_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DefaultTaskConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultTaskConfig) ProtoMessage() {}

func (x *DefaultTaskConfig) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_task_plugin_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultTaskConfig.ProtoReflect.Descriptor instead.
func (*DefaultTaskConfig) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_task_plugin_proto_rawDescGZIP(), []int{7}
}

type TaskAssets struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Assets []*TaskAssets_Asset `protobuf:"bytes,1,rep,name=assets,proto3" json:"assets,omitempty"`
}

func (x *TaskAssets) Reset() {
	*x = TaskAssets{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_task_plugin_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskAssets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAssets) ProtoMessage() {}

func (x *TaskAssets) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_task_plugin_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskAssets.ProtoReflect.Descriptor instead.
func (*TaskAssets) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_task_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *TaskAssets) GetAssets() []*TaskAssets_Asset {
	if x != nil {
		return x.Assets
	}
	return nil
}

type DefaultTaskAssets struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DefaultTaskAssets) Reset() {
	*x = DefaultTaskAssets{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_task_plugin_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DefaultTaskAssets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultTaskAssets) ProtoMessage() {}

func (x *DefaultTaskAssets) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_task_plugin_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultTaskAssets.ProtoReflect.Descriptor instead.
func (*DefaultTaskAssets) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_task_plugin_proto_rawDescGZIP(), []int{9}
}

type TaskWindow struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Size       *durationpb.Duration `protobuf:"bytes,1,opt,name=size,proto3" json:"size,omitempty"`
	Offset     *durationpb.Duration `protobuf:"bytes,2,opt,name=offset,proto3" json:"offset,omitempty"`
	TruncateTo string               `protobuf:"bytes,3,opt,name=truncate_to,json=truncateTo,proto3" json:"truncate_to,omitempty"`
}

func (x *TaskWindow) Reset() {
	*x = TaskWindow{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_task_plugin_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskWindow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskWindow) ProtoMessage() {}

func (x *TaskWindow) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_task_plugin_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskWindow.ProtoReflect.Descriptor instead.
func (*TaskWindow) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_task_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *TaskWindow) GetSize() *durationpb.Duration {
	if x != nil {
		return x.Size
	}
	return nil
}

func (x *TaskWindow) GetOffset() *durationpb.Duration {
	if x != nil {
		return x.Offset
	}
	return nil
}

func (x *TaskWindow) GetTruncateTo() string {
	if x != nil {
		return x.TruncateTo
	}
	return ""
}

type CompileTaskAssets struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CompileTaskAssets) Reset() {
	*x = CompileTaskAssets{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_task_plugin_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompileTaskAssets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileTaskAssets) ProtoMessage() {}

func (x *CompileTaskAssets) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_task_plugin_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompileTaskAssets.ProtoReflect.Descriptor instead.
func (*CompileTaskAssets) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_task_plugin_proto_rawDescGZIP(), []int{11}
}

type GenerateTaskDestination struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GenerateTaskDestination) Reset() {
	*x = GenerateTaskDestination{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_task_plugin_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateTaskDestination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateTaskDestination) ProtoMessage() {}

func (x *GenerateTaskDestination) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_task_plugin_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateTaskDestination.ProtoReflect.Descriptor instead.
func (*GenerateTaskDestination) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_task_plugin_proto_rawDescGZIP(), []int{12}
}

type GenerateTaskDependencies struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GenerateTaskDependencies) Reset() {
	*x = GenerateTaskDependencies{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_task_plugin_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateTaskDependencies) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateTaskDependencies) ProtoMessage() {}

func (x *GenerateTaskDependencies) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_task_plugin_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateTaskDependencies.ProtoReflect.Descriptor instead.
func (*GenerateTaskDependencies) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_task_plugin_proto_rawDescGZIP(), []int{13}
}

type GetTaskSchema_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetTaskSchema_Request) Reset() {
	*x = GetTaskSchema_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_task_plugin_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTaskSchema_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskSchema_Request) ProtoMessage() {}

func (x *GetTaskSchema_Request) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_task_plugin_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskSchema_Request.ProtoReflect.Descriptor instead.
func (*GetTaskSchema_Request) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_task_plugin_proto_rawDescGZIP(), []int{1, 0}
}

type GetTaskSchema_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Image       string `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	// secret_path will be mounted inside the container as volume
	// e.g. /opt/secret/auth.json
	SecretPath string `protobuf:"bytes,4,opt,name=secret_path,json=secretPath,proto3" json:"secret_path,omitempty"`
}

func (x *GetTaskSchema_Response) Reset() {
	*x = GetTaskSchema_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_task_plugin_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTaskSchema_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskSchema_Response) ProtoMessage() {}

func (x *GetTaskSchema_Response) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_task_plugin_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskSchema_Response.ProtoReflect.Descriptor instead.
func (*GetTaskSchema_Response) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_task_plugin_proto_rawDescGZIP(), []int{1, 1}
}

func (x *GetTaskSchema_Response) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetTaskSchema_Response) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetTaskSchema_Response) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *GetTaskSchema_Response) GetSecretPath() string {
	if x != nil {
		return x.SecretPath
	}
	return ""
}

type GetTaskQuestions_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Options *PluginOptions `protobuf:"bytes,40,opt,name=options,proto3" json:"options,omitempty"`
}

func (x *GetTaskQuestions_Request) Reset() {
	*x = GetTaskQuestions_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_task_plugin_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTaskQuestions_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskQuestions_Request) ProtoMessage() {}

func (x *GetTaskQuestions_Request) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_task_plugin_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskQuestions_Request.ProtoReflect.Descriptor instead.
func (*GetTaskQuestions_Request) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_task_plugin_proto_rawDescGZIP(), []int{4, 0}
}

func (x *GetTaskQuestions_Request) GetOptions() *PluginOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type GetTaskQuestions_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Questions []*PluginQuestion `protobuf:"bytes,1,rep,name=questions,proto3" json:"questions,omitempty"`
}

func (x *GetTaskQuestions_Response) Reset() {
	*x = GetTaskQuestions_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_task_plugin_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTaskQuestions_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskQuestions_Response) ProtoMessage() {}

func (x *GetTaskQuestions_Response) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_task_plugin_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskQuestions_Response.ProtoReflect.Descriptor instead.
func (*GetTaskQuestions_Response) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_task_plugin_proto_rawDescGZIP(), []int{4, 1}
}

func (x *GetTaskQuestions_Response) GetQuestions() []*PluginQuestion {
	if x != nil {
		return x.Questions
	}
	return nil
}

type ValidateTaskQuestion_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Answer  *PluginAnswer  `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	Options *PluginOptions `protobuf:"bytes,40,opt,name=options,proto3" json:"options,omitempty"`
}

func (x *ValidateTaskQuestion_Request) Reset() {
	*x = ValidateTaskQuestion_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_task_plugin_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateTaskQuestion_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTaskQuestion_Request) ProtoMessage() {}

func (x *ValidateTaskQuestion_Request) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_task_plugin_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTaskQuestion_Request.ProtoReflect.Descriptor instead.
func (*ValidateTaskQuestion_Request) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_task_plugin_proto_rawDescGZIP(), []int{5, 0}
}

func (x *ValidateTaskQuestion_Request) GetAnswer() *PluginAnswer {
	if x != nil {
		return x.Answer
	}
	return nil
}

func (x *ValidateTaskQuestion_Request) GetOptions() *PluginOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type ValidateTaskQuestion_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ValidateTaskQuestion_Response) Reset() {
	*x = ValidateTaskQuestion_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_task_plugin_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateTaskQuestion_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTaskQuestion_Response) ProtoMessage() {}

func (x *ValidateTaskQuestion_Response) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_task_plugin_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTaskQuestion_Response.ProtoReflect.Descriptor instead.
func (*ValidateTaskQuestion_Response) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_task_plugin_proto_rawDescGZIP(), []int{5, 1}
}

func (x *ValidateTaskQuestion_Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ValidateTaskQuestion_Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type TaskConfigs_Config struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *TaskConfigs_Config) Reset() {
	*x = TaskConfigs_Config{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_task_plugin_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskConfigs_Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskConfigs_Config) ProtoMessage() {}

func (x *TaskConfigs_Config) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_task_plugin_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskConfigs_Config.ProtoReflect.Descriptor instead.
func (*TaskConfigs_Config) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_task_plugin_proto_rawDescGZIP(), []int{6, 0}
}

func (x *TaskConfigs_Config) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TaskConfigs_Config) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type DefaultTaskConfig_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Answers []*PluginAnswer `protobuf:"bytes,1,rep,name=answers,proto3" json:"answers,omitempty"`
	Options *PluginOptions  `protobuf:"bytes,40,opt,name=options,proto3" json:"options,omitempty"`
}

func (x *DefaultTaskConfig_Request) Reset() {
	*x = DefaultTaskConfig_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_task_plugin_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DefaultTaskConfig_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultTaskConfig_Request) ProtoMessage() {}

func (x *DefaultTaskConfig_Request) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_task_plugin_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultTaskConfig_Request.ProtoReflect.Descriptor instead.
func (*DefaultTaskConfig_Request) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_task_plugin_proto_rawDescGZIP(), []int{7, 0}
}

func (x *DefaultTaskConfig_Request) GetAnswers() []*PluginAnswer {
	if x != nil {
		return x.Answers
	}
	return nil
}

func (x *DefaultTaskConfig_Request) GetOptions() *PluginOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type DefaultTaskConfig_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Configs *TaskConfigs `protobuf:"bytes,1,opt,name=configs,proto3" json:"configs,omitempty"`
}

func (x *DefaultTaskConfig_Response) Reset() {
	*x = DefaultTaskConfig_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_task_plugin_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DefaultTaskConfig_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultTaskConfig_Response) ProtoMessage() {}

func (x *DefaultTaskConfig_Response) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_task_plugin_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultTaskConfig_Response.ProtoReflect.Descriptor instead.
func (*DefaultTaskConfig_Response) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_task_plugin_proto_rawDescGZIP(), []int{7, 1}
}

func (x *DefaultTaskConfig_Response) GetConfigs() *TaskConfigs {
	if x != nil {
		return x.Configs
	}
	return nil
}

type TaskAssets_Asset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *TaskAssets_Asset) Reset() {
	*x = TaskAssets_Asset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_task_plugin_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskAssets_Asset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAssets_Asset) ProtoMessage() {}

func (x *TaskAssets_Asset) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_task_plugin_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskAssets_Asset.ProtoReflect.Descriptor instead.
func (*TaskAssets_Asset) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_task_plugin_proto_rawDescGZIP(), []int{8, 0}
}

func (x *TaskAssets_Asset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TaskAssets_Asset) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type DefaultTaskAssets_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Answers []*PluginAnswer `protobuf:"bytes,1,rep,name=answers,proto3" json:"answers,omitempty"`
	Options *PluginOptions  `protobuf:"bytes,40,opt,name=options,proto3" json:"options,omitempty"`
}

func (x *DefaultTaskAssets_Request) Reset() {
	*x = DefaultTaskAssets_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_task_plugin_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DefaultTaskAssets_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultTaskAssets_Request) ProtoMessage() {}

func (x *DefaultTaskAssets_Request) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_task_plugin_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultTaskAssets_Request.ProtoReflect.Descriptor instead.
func (*DefaultTaskAssets_Request) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_task_plugin_proto_rawDescGZIP(), []int{9, 0}
}

func (x *DefaultTaskAssets_Request) GetAnswers() []*PluginAnswer {
	if x != nil {
		return x.Answers
	}
	return nil
}

func (x *DefaultTaskAssets_Request) GetOptions() *PluginOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type DefaultTaskAssets_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Assets *TaskAssets `protobuf:"bytes,1,opt,name=assets,proto3" json:"assets,omitempty"`
}

func (x *DefaultTaskAssets_Response) Reset() {
	*x = DefaultTaskAssets_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_task_plugin_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DefaultTaskAssets_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultTaskAssets_Response) ProtoMessage() {}

func (x *DefaultTaskAssets_Response) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_task_plugin_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultTaskAssets_Response.ProtoReflect.Descriptor instead.
func (*DefaultTaskAssets_Response) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_task_plugin_proto_rawDescGZIP(), []int{9, 1}
}

func (x *DefaultTaskAssets_Response) GetAssets() *TaskAssets {
	if x != nil {
		return x.Assets
	}
	return nil
}

type CompileTaskAssets_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobConfigs       *TaskConfigs           `protobuf:"bytes,1,opt,name=job_configs,json=jobConfigs,proto3" json:"job_configs,omitempty"`
	JobAssets        *TaskAssets            `protobuf:"bytes,2,opt,name=job_assets,json=jobAssets,proto3" json:"job_assets,omitempty"`
	TaskWindow       *TaskWindow            `protobuf:"bytes,3,opt,name=task_window,json=taskWindow,proto3" json:"task_window,omitempty"`
	InstanceSchedule *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=instance_schedule,json=instanceSchedule,proto3" json:"instance_schedule,omitempty"`
	InstanceData     []*InstanceSpecData    `protobuf:"bytes,5,rep,name=instance_data,json=instanceData,proto3" json:"instance_data,omitempty"`
	Options          *PluginOptions         `protobuf:"bytes,40,opt,name=options,proto3" json:"options,omitempty"`
}

func (x *CompileTaskAssets_Request) Reset() {
	*x = CompileTaskAssets_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_task_plugin_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompileTaskAssets_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileTaskAssets_Request) ProtoMessage() {}

func (x *CompileTaskAssets_Request) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_task_plugin_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompileTaskAssets_Request.ProtoReflect.Descriptor instead.
func (*CompileTaskAssets_Request) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_task_plugin_proto_rawDescGZIP(), []int{11, 0}
}

func (x *CompileTaskAssets_Request) GetJobConfigs() *TaskConfigs {
	if x != nil {
		return x.JobConfigs
	}
	return nil
}

func (x *CompileTaskAssets_Request) GetJobAssets() *TaskAssets {
	if x != nil {
		return x.JobAssets
	}
	return nil
}

func (x *CompileTaskAssets_Request) GetTaskWindow() *TaskWindow {
	if x != nil {
		return x.TaskWindow
	}
	return nil
}

func (x *CompileTaskAssets_Request) GetInstanceSchedule() *timestamppb.Timestamp {
	if x != nil {
		return x.InstanceSchedule
	}
	return nil
}

func (x *CompileTaskAssets_Request) GetInstanceData() []*InstanceSpecData {
	if x != nil {
		return x.InstanceData
	}
	return nil
}

func (x *CompileTaskAssets_Request) GetOptions() *PluginOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type CompileTaskAssets_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Assets *TaskAssets `protobuf:"bytes,1,opt,name=assets,proto3" json:"assets,omitempty"`
}

func (x *CompileTaskAssets_Response) Reset() {
	*x = CompileTaskAssets_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_task_plugin_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompileTaskAssets_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileTaskAssets_Response) ProtoMessage() {}

func (x *CompileTaskAssets_Response) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_task_plugin_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompileTaskAssets_Response.ProtoReflect.Descriptor instead.
func (*CompileTaskAssets_Response) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_task_plugin_proto_rawDescGZIP(), []int{11, 1}
}

func (x *CompileTaskAssets_Response) GetAssets() *TaskAssets {
	if x != nil {
		return x.Assets
	}
	return nil
}

type GenerateTaskDestination_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Task configs
	JobConfig *TaskConfigs `protobuf:"bytes,1,opt,name=job_config,json=jobConfig,proto3" json:"job_config,omitempty"`
	// Job assets
	JobAssets *TaskAssets `protobuf:"bytes,2,opt,name=job_assets,json=jobAssets,proto3" json:"job_assets,omitempty"`
	// Job project
	Project *ProjectSpecification `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	Options *PluginOptions        `protobuf:"bytes,40,opt,name=options,proto3" json:"options,omitempty"`
}

func (x *GenerateTaskDestination_Request) Reset() {
	*x = GenerateTaskDestination_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_task_plugin_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateTaskDestination_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateTaskDestination_Request) ProtoMessage() {}

func (x *GenerateTaskDestination_Request) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_task_plugin_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateTaskDestination_Request.ProtoReflect.Descriptor instead.
func (*GenerateTaskDestination_Request) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_task_plugin_proto_rawDescGZIP(), []int{12, 0}
}

func (x *GenerateTaskDestination_Request) GetJobConfig() *TaskConfigs {
	if x != nil {
		return x.JobConfig
	}
	return nil
}

func (x *GenerateTaskDestination_Request) GetJobAssets() *TaskAssets {
	if x != nil {
		return x.JobAssets
	}
	return nil
}

func (x *GenerateTaskDestination_Request) GetProject() *ProjectSpecification {
	if x != nil {
		return x.Project
	}
	return nil
}

func (x *GenerateTaskDestination_Request) GetOptions() *PluginOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type GenerateTaskDestination_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Destination string `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"`
}

func (x *GenerateTaskDestination_Response) Reset() {
	*x = GenerateTaskDestination_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_task_plugin_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateTaskDestination_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateTaskDestination_Response) ProtoMessage() {}

func (x *GenerateTaskDestination_Response) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_task_plugin_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateTaskDestination_Response.ProtoReflect.Descriptor instead.
func (*GenerateTaskDestination_Response) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_task_plugin_proto_rawDescGZIP(), []int{12, 1}
}

func (x *GenerateTaskDestination_Response) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

type GenerateTaskDependencies_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Task configs
	JobConfig *TaskConfigs `protobuf:"bytes,1,opt,name=job_config,json=jobConfig,proto3" json:"job_config,omitempty"`
	// Job assets
	JobAssets *TaskAssets `protobuf:"bytes,2,opt,name=job_assets,json=jobAssets,proto3" json:"job_assets,omitempty"`
	// Job project
	Project *ProjectSpecification `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	Options *PluginOptions        `protobuf:"bytes,40,opt,name=options,proto3" json:"options,omitempty"`
}

func (x *GenerateTaskDependencies_Request) Reset() {
	*x = GenerateTaskDependencies_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_task_plugin_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateTaskDependencies_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateTaskDependencies_Request) ProtoMessage() {}

func (x *GenerateTaskDependencies_Request) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_task_plugin_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateTaskDependencies_Request.ProtoReflect.Descriptor instead.
func (*GenerateTaskDependencies_Request) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_task_plugin_proto_rawDescGZIP(), []int{13, 0}
}

func (x *GenerateTaskDependencies_Request) GetJobConfig() *TaskConfigs {
	if x != nil {
		return x.JobConfig
	}
	return nil
}

func (x *GenerateTaskDependencies_Request) GetJobAssets() *TaskAssets {
	if x != nil {
		return x.JobAssets
	}
	return nil
}

func (x *GenerateTaskDependencies_Request) GetProject() *ProjectSpecification {
	if x != nil {
		return x.Project
	}
	return nil
}

func (x *GenerateTaskDependencies_Request) GetOptions() *PluginOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type GenerateTaskDependencies_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dependencies []string `protobuf:"bytes,1,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
}

func (x *GenerateTaskDependencies_Response) Reset() {
	*x = GenerateTaskDependencies_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_task_plugin_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateTaskDependencies_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateTaskDependencies_Response) ProtoMessage() {}

func (x *GenerateTaskDependencies_Response) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_task_plugin_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateTaskDependencies_Response.ProtoReflect.Descriptor instead.
func (*GenerateTaskDependencies_Response) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_task_plugin_proto_rawDescGZIP(), []int{13, 1}
}

func (x *GenerateTaskDependencies_Response) GetDependencies() []string {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

var File_odpf_optimus_task_plugin_proto protoreflect.FileDescriptor

var file_odpf_optimus_task_plugin_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x6f, 0x64, 0x70, 0x66, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2f, 0x74,
	0x61, 0x73, 0x6b, 0x5f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0c, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x1a, 0x22,
	0x6f, 0x64, 0x70, 0x66, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2f, 0x72, 0x75, 0x6e,
	0x74, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x28, 0x0a, 0x0d, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x64, 0x72, 0x79, 0x5f, 0x72, 0x75, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x64, 0x72, 0x79, 0x52, 0x75, 0x6e, 0x22, 0x93, 0x01,
	0x0a, 0x0d, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x1a,
	0x09, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x77, 0x0a, 0x08, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x5f, 0x70, 0x61, 0x74,
	0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x50,
	0x61, 0x74, 0x68, 0x22, 0x84, 0x02, 0x0a, 0x0e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x51, 0x75,
	0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72,
	0x6f, 0x6d, 0x70, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x6f, 0x6d,
	0x70, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x65, 0x6c, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x68, 0x65, 0x6c, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74,
	0x12, 0x20, 0x0a, 0x0b, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x73, 0x65, 0x6c, 0x65,
	0x63, 0x74, 0x12, 0x33, 0x0a, 0x16, 0x73, 0x75, 0x62, 0x5f, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x5f, 0x69, 0x66, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x13, 0x73, 0x75, 0x62, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x49, 0x66, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x41, 0x0a, 0x0d, 0x73, 0x75, 0x62, 0x5f, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x50, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x73, 0x75,
	0x62, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x5e, 0x0a, 0x0c, 0x50, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x38, 0x0a, 0x08, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6f,
	0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x50, 0x6c, 0x75, 0x67,
	0x69, 0x6e, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x9c, 0x01, 0x0a, 0x10, 0x47,
	0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a,
	0x40, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x07, 0x6f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x28, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6f, 0x64,
	0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x1a, 0x46, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a,
	0x09, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e,
	0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0xc8, 0x01, 0x0a, 0x14, 0x56, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69,
	0x6f, 0x6e, 0x1a, 0x74, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x32, 0x0a,
	0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x50, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65,
	0x72, 0x12, 0x35, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x28, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75,
	0x73, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52,
	0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x3a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x22, 0x7d, 0x0a, 0x0b, 0x54, 0x61, 0x73, 0x6b, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x73, 0x12, 0x3a, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69,
	0x6d, 0x75, 0x73, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x2e,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x1a,
	0x32, 0x0a, 0x06, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x22, 0xcc, 0x01, 0x0a, 0x11, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x54,
	0x61, 0x73, 0x6b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x1a, 0x76, 0x0a, 0x07, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x34, 0x0a, 0x07, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74,
	0x69, 0x6d, 0x75, 0x73, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x41, 0x6e, 0x73, 0x77, 0x65,
	0x72, 0x52, 0x07, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x12, 0x35, 0x0a, 0x07, 0x6f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x28, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6f, 0x64,
	0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x1a, 0x3f, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a,
	0x07, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x54, 0x61,
	0x73, 0x6b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x73, 0x22, 0x77, 0x0a, 0x0a, 0x54, 0x61, 0x73, 0x6b, 0x41, 0x73, 0x73, 0x65, 0x74, 0x73,
	0x12, 0x36, 0x0a, 0x06, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1e, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e,
	0x54, 0x61, 0x73, 0x6b, 0x41, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2e, 0x41, 0x73, 0x73, 0x65, 0x74,
	0x52, 0x06, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x1a, 0x31, 0x0a, 0x05, 0x41, 0x73, 0x73, 0x65,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xc9, 0x01, 0x0a, 0x11,
	0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x41, 0x73, 0x73, 0x65, 0x74,
	0x73, 0x1a, 0x76, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x34, 0x0a, 0x07,
	0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x50, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x07, 0x61, 0x6e, 0x73, 0x77, 0x65,
	0x72, 0x73, 0x12, 0x35, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x28, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d,
	0x75, 0x73, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x3c, 0x0a, 0x08, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x06, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74,
	0x69, 0x6d, 0x75, 0x73, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x41, 0x73, 0x73, 0x65, 0x74, 0x73, 0x52,
	0x06, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x22, 0x8f, 0x01, 0x0a, 0x0a, 0x54, 0x61, 0x73, 0x6b,
	0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x12, 0x2d, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x31, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x72, 0x75, 0x6e,
	0x63, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74,
	0x72, 0x75, 0x6e, 0x63, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x22, 0xd2, 0x03, 0x0a, 0x11, 0x43, 0x6f,
	0x6d, 0x70, 0x69, 0x6c, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x41, 0x73, 0x73, 0x65, 0x74, 0x73, 0x1a,
	0xfe, 0x02, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3a, 0x0a, 0x0b, 0x6a,
	0x6f, 0x62, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e,
	0x54, 0x61, 0x73, 0x6b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x52, 0x0a, 0x6a, 0x6f, 0x62,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x12, 0x37, 0x0a, 0x0a, 0x6a, 0x6f, 0x62, 0x5f, 0x61,
	0x73, 0x73, 0x65, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6f, 0x64,
	0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x41,
	0x73, 0x73, 0x65, 0x74, 0x73, 0x52, 0x09, 0x6a, 0x6f, 0x62, 0x41, 0x73, 0x73, 0x65, 0x74, 0x73,
	0x12, 0x39, 0x0a, 0x0b, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74,
	0x69, 0x6d, 0x75, 0x73, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x52,
	0x0a, 0x74, 0x61, 0x73, 0x6b, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x12, 0x47, 0x0a, 0x11, 0x69,
	0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x10, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x53, 0x63, 0x68, 0x65,
	0x64, 0x75, 0x6c, 0x65, 0x12, 0x43, 0x0a, 0x0d, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6f, 0x64,
	0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x53, 0x70, 0x65, 0x63, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0c, 0x69, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x35, 0x0a, 0x07, 0x6f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0x28, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6f, 0x64, 0x70,
	0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x1a, 0x3c, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x06,
	0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6f,
	0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x54, 0x61, 0x73, 0x6b,
	0x41, 0x73, 0x73, 0x65, 0x74, 0x73, 0x52, 0x06, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x22, 0xbb,
	0x02, 0x0a, 0x17, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x44,
	0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0xf1, 0x01, 0x0a, 0x07, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x38, 0x0a, 0x0a, 0x6a, 0x6f, 0x62, 0x5f, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6f, 0x64, 0x70,
	0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x73, 0x52, 0x09, 0x6a, 0x6f, 0x62, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x12, 0x37, 0x0a, 0x0a, 0x6a, 0x6f, 0x62, 0x5f, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69,
	0x6d, 0x75, 0x73, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x41, 0x73, 0x73, 0x65, 0x74, 0x73, 0x52, 0x09,
	0x6a, 0x6f, 0x62, 0x41, 0x73, 0x73, 0x65, 0x74, 0x73, 0x12, 0x3c, 0x0a, 0x07, 0x70, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6f, 0x64, 0x70,
	0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63,
	0x74, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07,
	0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x35, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0x28, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e,
	0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x2c,
	0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65,
	0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xbe, 0x02, 0x0a,
	0x18, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x44, 0x65, 0x70,
	0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x1a, 0xf1, 0x01, 0x0a, 0x07, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x38, 0x0a, 0x0a, 0x6a, 0x6f, 0x62, 0x5f, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6f, 0x64, 0x70, 0x66,
	0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x73, 0x52, 0x09, 0x6a, 0x6f, 0x62, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12,
	0x37, 0x0a, 0x0a, 0x6a, 0x6f, 0x62, 0x5f, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d,
	0x75, 0x73, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x41, 0x73, 0x73, 0x65, 0x74, 0x73, 0x52, 0x09, 0x6a,
	0x6f, 0x62, 0x41, 0x73, 0x73, 0x65, 0x74, 0x73, 0x12, 0x3c, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6f, 0x64, 0x70, 0x66,
	0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x70,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x35, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0x28, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f,
	0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x2e, 0x0a,
	0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x64, 0x65, 0x70,
	0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x0c, 0x64, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x32, 0xed, 0x06,
	0x0a, 0x0a, 0x54, 0x61, 0x73, 0x6b, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x12, 0x5a, 0x0a, 0x0d,
	0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x12, 0x23, 0x2e,
	0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x47, 0x65, 0x74,
	0x54, 0x61, 0x73, 0x6b, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x24, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75,
	0x73, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x63, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x54,
	0x61, 0x73, 0x6b, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x26, 0x2e, 0x6f,
	0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x54,
	0x61, 0x73, 0x6b, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69,
	0x6d, 0x75, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x51, 0x75, 0x65, 0x73, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6f, 0x0a,
	0x14, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x51, 0x75, 0x65,
	0x73, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2a, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74,
	0x69, 0x6d, 0x75, 0x73, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x54, 0x61, 0x73,
	0x6b, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x2b, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73,
	0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x51, 0x75, 0x65,
	0x73, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x66,
	0x0a, 0x11, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x12, 0x27, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d,
	0x75, 0x73, 0x2e, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x6f,
	0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x44, 0x65, 0x66, 0x61,
	0x75, 0x6c, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x66, 0x0a, 0x11, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c,
	0x74, 0x54, 0x61, 0x73, 0x6b, 0x41, 0x73, 0x73, 0x65, 0x74, 0x73, 0x12, 0x27, 0x2e, 0x6f, 0x64,
	0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x44, 0x65, 0x66, 0x61, 0x75,
	0x6c, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x41, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69,
	0x6d, 0x75, 0x73, 0x2e, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x41,
	0x73, 0x73, 0x65, 0x74, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x66,
	0x0a, 0x11, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x41, 0x73, 0x73,
	0x65, 0x74, 0x73, 0x12, 0x27, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d,
	0x75, 0x73, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x41, 0x73,
	0x73, 0x65, 0x74, 0x73, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x6f,
	0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x43, 0x6f, 0x6d, 0x70,
	0x69, 0x6c, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x41, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x78, 0x0a, 0x17, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x2d, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73,
	0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x44, 0x65, 0x73,
	0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x2e, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e,
	0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x44, 0x65, 0x73, 0x74,
	0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x7b, 0x0a, 0x18, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b,
	0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x12, 0x2e, 0x2e, 0x6f,
	0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x47, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e,
	0x63, 0x69, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2f, 0x2e, 0x6f,
	0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x47, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e,
	0x63, 0x69, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x4d, 0x0a,
	0x16, 0x69, 0x6f, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6e, 0x2e,
	0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x42, 0x11, 0x54, 0x61, 0x73, 0x6b, 0x50, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x50, 0x01, 0x5a, 0x1e, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x64, 0x70, 0x66, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x6e, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_odpf_optimus_task_plugin_proto_rawDescOnce sync.Once
	file_odpf_optimus_task_plugin_proto_rawDescData = file_odpf_optimus_task_plugin_proto_rawDesc
)

func file_odpf_optimus_task_plugin_proto_rawDescGZIP() []byte {
	file_odpf_optimus_task_plugin_proto_rawDescOnce.Do(func() {
		file_odpf_optimus_task_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(file_odpf_optimus_task_plugin_proto_rawDescData)
	})
	return file_odpf_optimus_task_plugin_proto_rawDescData
}

var file_odpf_optimus_task_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_odpf_optimus_task_plugin_proto_goTypes = []interface{}{
	(*PluginOptions)(nil),                     // 0: odpf.optimus.PluginOptions
	(*GetTaskSchema)(nil),                     // 1: odpf.optimus.GetTaskSchema
	(*PluginQuestion)(nil),                    // 2: odpf.optimus.PluginQuestion
	(*PluginAnswer)(nil),                      // 3: odpf.optimus.PluginAnswer
	(*GetTaskQuestions)(nil),                  // 4: odpf.optimus.GetTaskQuestions
	(*ValidateTaskQuestion)(nil),              // 5: odpf.optimus.ValidateTaskQuestion
	(*TaskConfigs)(nil),                       // 6: odpf.optimus.TaskConfigs
	(*DefaultTaskConfig)(nil),                 // 7: odpf.optimus.DefaultTaskConfig
	(*TaskAssets)(nil),                        // 8: odpf.optimus.TaskAssets
	(*DefaultTaskAssets)(nil),                 // 9: odpf.optimus.DefaultTaskAssets
	(*TaskWindow)(nil),                        // 10: odpf.optimus.TaskWindow
	(*CompileTaskAssets)(nil),                 // 11: odpf.optimus.CompileTaskAssets
	(*GenerateTaskDestination)(nil),           // 12: odpf.optimus.GenerateTaskDestination
	(*GenerateTaskDependencies)(nil),          // 13: odpf.optimus.GenerateTaskDependencies
	(*GetTaskSchema_Request)(nil),             // 14: odpf.optimus.GetTaskSchema.Request
	(*GetTaskSchema_Response)(nil),            // 15: odpf.optimus.GetTaskSchema.Response
	(*GetTaskQuestions_Request)(nil),          // 16: odpf.optimus.GetTaskQuestions.Request
	(*GetTaskQuestions_Response)(nil),         // 17: odpf.optimus.GetTaskQuestions.Response
	(*ValidateTaskQuestion_Request)(nil),      // 18: odpf.optimus.ValidateTaskQuestion.Request
	(*ValidateTaskQuestion_Response)(nil),     // 19: odpf.optimus.ValidateTaskQuestion.Response
	(*TaskConfigs_Config)(nil),                // 20: odpf.optimus.TaskConfigs.Config
	(*DefaultTaskConfig_Request)(nil),         // 21: odpf.optimus.DefaultTaskConfig.Request
	(*DefaultTaskConfig_Response)(nil),        // 22: odpf.optimus.DefaultTaskConfig.Response
	(*TaskAssets_Asset)(nil),                  // 23: odpf.optimus.TaskAssets.Asset
	(*DefaultTaskAssets_Request)(nil),         // 24: odpf.optimus.DefaultTaskAssets.Request
	(*DefaultTaskAssets_Response)(nil),        // 25: odpf.optimus.DefaultTaskAssets.Response
	(*CompileTaskAssets_Request)(nil),         // 26: odpf.optimus.CompileTaskAssets.Request
	(*CompileTaskAssets_Response)(nil),        // 27: odpf.optimus.CompileTaskAssets.Response
	(*GenerateTaskDestination_Request)(nil),   // 28: odpf.optimus.GenerateTaskDestination.Request
	(*GenerateTaskDestination_Response)(nil),  // 29: odpf.optimus.GenerateTaskDestination.Response
	(*GenerateTaskDependencies_Request)(nil),  // 30: odpf.optimus.GenerateTaskDependencies.Request
	(*GenerateTaskDependencies_Response)(nil), // 31: odpf.optimus.GenerateTaskDependencies.Response
	(*durationpb.Duration)(nil),               // 32: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil),             // 33: google.protobuf.Timestamp
	(*InstanceSpecData)(nil),                  // 34: odpf.optimus.InstanceSpecData
	(*ProjectSpecification)(nil),              // 35: odpf.optimus.ProjectSpecification
}
var file_odpf_optimus_task_plugin_proto_depIdxs = []int32{
	2,  // 0: odpf.optimus.PluginQuestion.sub_questions:type_name -> odpf.optimus.PluginQuestion
	2,  // 1: odpf.optimus.PluginAnswer.question:type_name -> odpf.optimus.PluginQuestion
	20, // 2: odpf.optimus.TaskConfigs.configs:type_name -> odpf.optimus.TaskConfigs.Config
	23, // 3: odpf.optimus.TaskAssets.assets:type_name -> odpf.optimus.TaskAssets.Asset
	32, // 4: odpf.optimus.TaskWindow.size:type_name -> google.protobuf.Duration
	32, // 5: odpf.optimus.TaskWindow.offset:type_name -> google.protobuf.Duration
	0,  // 6: odpf.optimus.GetTaskQuestions.Request.options:type_name -> odpf.optimus.PluginOptions
	2,  // 7: odpf.optimus.GetTaskQuestions.Response.questions:type_name -> odpf.optimus.PluginQuestion
	3,  // 8: odpf.optimus.ValidateTaskQuestion.Request.answer:type_name -> odpf.optimus.PluginAnswer
	0,  // 9: odpf.optimus.ValidateTaskQuestion.Request.options:type_name -> odpf.optimus.PluginOptions
	3,  // 10: odpf.optimus.DefaultTaskConfig.Request.answers:type_name -> odpf.optimus.PluginAnswer
	0,  // 11: odpf.optimus.DefaultTaskConfig.Request.options:type_name -> odpf.optimus.PluginOptions
	6,  // 12: odpf.optimus.DefaultTaskConfig.Response.configs:type_name -> odpf.optimus.TaskConfigs
	3,  // 13: odpf.optimus.DefaultTaskAssets.Request.answers:type_name -> odpf.optimus.PluginAnswer
	0,  // 14: odpf.optimus.DefaultTaskAssets.Request.options:type_name -> odpf.optimus.PluginOptions
	8,  // 15: odpf.optimus.DefaultTaskAssets.Response.assets:type_name -> odpf.optimus.TaskAssets
	6,  // 16: odpf.optimus.CompileTaskAssets.Request.job_configs:type_name -> odpf.optimus.TaskConfigs
	8,  // 17: odpf.optimus.CompileTaskAssets.Request.job_assets:type_name -> odpf.optimus.TaskAssets
	10, // 18: odpf.optimus.CompileTaskAssets.Request.task_window:type_name -> odpf.optimus.TaskWindow
	33, // 19: odpf.optimus.CompileTaskAssets.Request.instance_schedule:type_name -> google.protobuf.Timestamp
	34, // 20: odpf.optimus.CompileTaskAssets.Request.instance_data:type_name -> odpf.optimus.InstanceSpecData
	0,  // 21: odpf.optimus.CompileTaskAssets.Request.options:type_name -> odpf.optimus.PluginOptions
	8,  // 22: odpf.optimus.CompileTaskAssets.Response.assets:type_name -> odpf.optimus.TaskAssets
	6,  // 23: odpf.optimus.GenerateTaskDestination.Request.job_config:type_name -> odpf.optimus.TaskConfigs
	8,  // 24: odpf.optimus.GenerateTaskDestination.Request.job_assets:type_name -> odpf.optimus.TaskAssets
	35, // 25: odpf.optimus.GenerateTaskDestination.Request.project:type_name -> odpf.optimus.ProjectSpecification
	0,  // 26: odpf.optimus.GenerateTaskDestination.Request.options:type_name -> odpf.optimus.PluginOptions
	6,  // 27: odpf.optimus.GenerateTaskDependencies.Request.job_config:type_name -> odpf.optimus.TaskConfigs
	8,  // 28: odpf.optimus.GenerateTaskDependencies.Request.job_assets:type_name -> odpf.optimus.TaskAssets
	35, // 29: odpf.optimus.GenerateTaskDependencies.Request.project:type_name -> odpf.optimus.ProjectSpecification
	0,  // 30: odpf.optimus.GenerateTaskDependencies.Request.options:type_name -> odpf.optimus.PluginOptions
	14, // 31: odpf.optimus.TaskPlugin.GetTaskSchema:input_type -> odpf.optimus.GetTaskSchema.Request
	16, // 32: odpf.optimus.TaskPlugin.GetTaskQuestions:input_type -> odpf.optimus.GetTaskQuestions.Request
	18, // 33: odpf.optimus.TaskPlugin.ValidateTaskQuestion:input_type -> odpf.optimus.ValidateTaskQuestion.Request
	21, // 34: odpf.optimus.TaskPlugin.DefaultTaskConfig:input_type -> odpf.optimus.DefaultTaskConfig.Request
	24, // 35: odpf.optimus.TaskPlugin.DefaultTaskAssets:input_type -> odpf.optimus.DefaultTaskAssets.Request
	26, // 36: odpf.optimus.TaskPlugin.CompileTaskAssets:input_type -> odpf.optimus.CompileTaskAssets.Request
	28, // 37: odpf.optimus.TaskPlugin.GenerateTaskDestination:input_type -> odpf.optimus.GenerateTaskDestination.Request
	30, // 38: odpf.optimus.TaskPlugin.GenerateTaskDependencies:input_type -> odpf.optimus.GenerateTaskDependencies.Request
	15, // 39: odpf.optimus.TaskPlugin.GetTaskSchema:output_type -> odpf.optimus.GetTaskSchema.Response
	17, // 40: odpf.optimus.TaskPlugin.GetTaskQuestions:output_type -> odpf.optimus.GetTaskQuestions.Response
	19, // 41: odpf.optimus.TaskPlugin.ValidateTaskQuestion:output_type -> odpf.optimus.ValidateTaskQuestion.Response
	22, // 42: odpf.optimus.TaskPlugin.DefaultTaskConfig:output_type -> odpf.optimus.DefaultTaskConfig.Response
	25, // 43: odpf.optimus.TaskPlugin.DefaultTaskAssets:output_type -> odpf.optimus.DefaultTaskAssets.Response
	27, // 44: odpf.optimus.TaskPlugin.CompileTaskAssets:output_type -> odpf.optimus.CompileTaskAssets.Response
	29, // 45: odpf.optimus.TaskPlugin.GenerateTaskDestination:output_type -> odpf.optimus.GenerateTaskDestination.Response
	31, // 46: odpf.optimus.TaskPlugin.GenerateTaskDependencies:output_type -> odpf.optimus.GenerateTaskDependencies.Response
	39, // [39:47] is the sub-list for method output_type
	31, // [31:39] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_odpf_optimus_task_plugin_proto_init() }
func file_odpf_optimus_task_plugin_proto_init() {
	if File_odpf_optimus_task_plugin_proto != nil {
		return
	}
	file_odpf_optimus_runtime_service_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_odpf_optimus_task_plugin_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PluginOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_task_plugin_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTaskSchema); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_task_plugin_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PluginQuestion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_task_plugin_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PluginAnswer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_task_plugin_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTaskQuestions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_task_plugin_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidateTaskQuestion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_task_plugin_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskConfigs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_task_plugin_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DefaultTaskConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_task_plugin_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskAssets); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_task_plugin_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DefaultTaskAssets); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_task_plugin_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskWindow); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_task_plugin_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompileTaskAssets); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_task_plugin_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateTaskDestination); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_task_plugin_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateTaskDependencies); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_task_plugin_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTaskSchema_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_task_plugin_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTaskSchema_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_task_plugin_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTaskQuestions_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_task_plugin_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTaskQuestions_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_task_plugin_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidateTaskQuestion_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_task_plugin_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidateTaskQuestion_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_task_plugin_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskConfigs_Config); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_task_plugin_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DefaultTaskConfig_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_task_plugin_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DefaultTaskConfig_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_task_plugin_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskAssets_Asset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_task_plugin_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DefaultTaskAssets_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_task_plugin_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DefaultTaskAssets_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_task_plugin_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompileTaskAssets_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_task_plugin_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompileTaskAssets_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_task_plugin_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateTaskDestination_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_task_plugin_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateTaskDestination_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_task_plugin_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateTaskDependencies_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_task_plugin_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateTaskDependencies_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_odpf_optimus_task_plugin_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_odpf_optimus_task_plugin_proto_goTypes,
		DependencyIndexes: file_odpf_optimus_task_plugin_proto_depIdxs,
		MessageInfos:      file_odpf_optimus_task_plugin_proto_msgTypes,
	}.Build()
	File_odpf_optimus_task_plugin_proto = out.File
	file_odpf_optimus_task_plugin_proto_rawDesc = nil
	file_odpf_optimus_task_plugin_proto_goTypes = nil
	file_odpf_optimus_task_plugin_proto_depIdxs = nil
}
