{
 "title": "Optimus Dashboard",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "SELECT name AS __text, id AS __value FROM namespace"
   },
   {
    "name": "project",
    "query": "SELECT name AS __text, id AS __value FROM project"
   },
   {
    "name": "job_id",
    "query": "select  job.name as __text , job_run.job_id as __value \nfrom job_run \ninner join job on job_run.job_id = job.id\nWHERE  $__timeFilter(scheduled_at)"
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Number jobs by dependency count",
   "type": "table",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "select dependency_count, count (*) as job_count from (\n\tselect k.name, count (*) as dependency_count from (\n\tSELECT name, jsonb_object_keys(dependencies)\n\t from job\n\t where\n\t\tdependencies IS NOT NULL\n\t\tAND dependencies <> 'null'\n\t) as k  group by name\n) as l group by dependency_count"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n\tn.name,\n\tcount(*)\nFROM\n\tjob \nJOIN namespace n ON n.id = job.namespace_id\nwhere job.project_id = '$project'\ngroup by n.name"
    }
   ]
  },
  {
   "title": "Namespaces",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  p.name,\n  count(*)\nFROM\n  namespace n\nJOIN project p ON p.id = n.project_id\nGROUP BY p.name\nORDER BY 1"
    }
   ]
  },
  {
   "title": "jobs count per task type",
   "type": "table",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT count(*) as jobs_count , task_name as task_type FROM job group by task_name  order by jobs_count desc\n"
    }
   ]
  },
  {
   "title": "Secrets",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  p.name,\n  count(*)\nFROM\n  secret s\nJOIN project p ON p.id = s.project_id\nGROUP BY p.name\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Namespaces",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM\n  namespace"
    }
   ]
  },
  {
   "title": "Projects",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM\n  project"
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM\n  job"
    }
   ]
  },
  { "title": "SLA Dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "SLA miss summary",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "select \n\tfiltered.job_id, job.name,\n\tROUND((filtered.count*100)/total.count::decimal, 2) as miss_percentage ,\n\tfiltered.max_delay , filtered.avg_delay, total.count as total_runs_in_interval\nfrom (\n\tselect \n\t\tcount(*) as count , \n\t\tjob_id , \n\t\tmax(duration) as max_delay, \n\t\tavg(duration) as avg_delay \n\tfrom job_run \n\twhere $__timeFilter(scheduled_at)\n\t\tAND  EXTRACT(EPOCH from least(end_time , now())- start_time) > sla_definition  \t\t\n        AND namespace_id = '$namespace' \n        AND project_id = '$project'\n\tgroup by job_id\n) as filtered \ninner join (\n\tselect count(*) , job_id \n\tfrom job_run \n\twhere $__timeFilter(scheduled_at) \n        AND namespace_id = '$namespace' \n        AND project_id = '$project'\n\tgroup by job_id\n) as total on total.job_id = filtered.job_id\ninner join job on job.id = filtered.job_id"
    }
   ]
  },
  {
   "title": "SLA missed last runs ",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "select job.name, \n\t\tlast_job_runs.scheduled_at,\n\t\tlast_job_runs.start_time , \n\t\tlast_job_runs.end_time,  \n\t\tEXTRACT(EPOCH from least(last_job_runs.end_time , now())- last_job_runs.start_time) as total_job_run_time, \n\t\tlast_job_runs.sla_definition  \nfrom \n\t(SELECT DISTINCT ON (job_id,scheduled_at ) * FROM job_run where $__timeFilter(scheduled_at) and  namespace_id = '$namespace' \n        AND project_id = '$project' ORDER BY job_id,scheduled_at, attempt DESC ) as last_job_runs\ninner join job \n\ton last_job_runs.job_id = job.id\n\twhere  EXTRACT(EPOCH from least(last_job_runs.end_time , now())- last_job_runs.start_time) > last_job_runs.sla_definition \n"
    }
   ]
  },
  {
   "title": "job rerun counts ",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT concat(job.name,'_',job_run.scheduled_at) as job_run_schedule, count(*) as reruns FROM job_run \ninner join job  on job_run.job_id = job.id\nwhere\n  $__timeFilter(scheduled_at) \n  AND job_run.namespace_id = '$namespace' \n  AND job_run.project_id = '$project'\ngroup by (job.name, job_run.job_id, job_run.scheduled_at  ) \n"
    }
   ]
  },
  {
   "title": "job durations",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "rawSql": "SELECT\n  timezone('utc',job_run.scheduled_at) as time,\n  job_run.attempt as attempt, \n  concat(timezone('utc',job_run.scheduled_at), '_',job_run.attempt ),\n  sensor_run.duration as sensor_duration,\n  task_run.duration as task_duration,\n  hook_run.duration as hook_duration\nFROM job_run\nleft join sensor_run  on sensor_run.job_run_id = job_run.job_run_id and sensor_run.job_run_attempt = job_run.attempt\nleft join task_run    on task_run.job_run_id = job_run.job_run_id and task_run.job_run_attempt = job_run.attempt\nleft join hook_run    on hook_run.job_run_id = job_run.job_run_id and hook_run.job_run_attempt = job_run.attempt\nWHERE\n  $__timeFilter(scheduled_at) \n  AND job_id = '$job_id' \n  AND namespace_id = '$namespace' \n  AND project_id = '$project'\n\nORDER BY scheduled_at , attempt"
    }
   ]
  }
 ]
}