package resolver_test

import (
	"context"
	"errors"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"

	"github.com/odpf/optimus/core/job"
	"github.com/odpf/optimus/core/job/dto"
	"github.com/odpf/optimus/core/job/resolver"
	"github.com/odpf/optimus/core/tenant"
)

func TestExternalUpstreamResolver(t *testing.T) {
	ctx := context.Background()
	externalTenant, _ := tenant.NewTenant("external-project", "external-namespace")

	t.Run("FetchExternalUpstreams", func(t *testing.T) {
		t.Run("resolves upstream externally", func(t *testing.T) {
			resourceManager := new(ResourceManager)

			rawUpstreams := []*dto.RawUpstream{
				{JobName: "job-B", ProjectName: externalTenant.ProjectName().String()},
				{ResourceURN: "resource-C"},
			}
			upstreamB, _ := job.NewUpstreamResolved("job-B", "external-host", "resource-B", externalTenant, "static")
			upstreamC, _ := job.NewUpstreamResolved("job-C", "external-host", "resource-C", externalTenant, "inferred")
			resourceManager.On("GetOptimusUpstreams", ctx, rawUpstreams[0]).Return([]*job.Upstream{upstreamB}, nil).Once()
			resourceManager.On("GetOptimusUpstreams", ctx, rawUpstreams[1]).Return([]*job.Upstream{upstreamC}, nil).Once()

			extUpstreamResolver := resolver.NewExternalUpstreamResolver([]resolver.ResourceManager{resourceManager})
			result, unresolvedDep, err := extUpstreamResolver.FetchExternalUpstreams(ctx, rawUpstreams)
			assert.Nil(t, unresolvedDep)
			assert.Nil(t, err)
			assert.EqualValues(t, []*job.Upstream{upstreamB, upstreamC}, result)
		})
		t.Run("returns unresolved upstream and upstream error if unable to fetch upstreams from external", func(t *testing.T) {
			resourceManager := new(ResourceManager)

			rawUpstreams := []*dto.RawUpstream{
				{JobName: "job-B", ProjectName: externalTenant.ProjectName().String()},
				{ResourceURN: "resource-C"},
			}
			upstreamB, _ := job.NewUpstreamResolved("job-B", "external-host", "resource-B", externalTenant, "static")
			resourceManager.On("GetOptimusUpstreams", ctx, rawUpstreams[0]).Return([]*job.Upstream{upstreamB}, nil).Once()
			resourceManager.On("GetOptimusUpstreams", ctx, rawUpstreams[1]).Return([]*job.Upstream{}, errors.New("connection error")).Once()

			extUpstreamResolver := resolver.NewExternalUpstreamResolver([]resolver.ResourceManager{resourceManager})
			result, unresolvedDep, err := extUpstreamResolver.FetchExternalUpstreams(ctx, rawUpstreams)
			assert.Equal(t, []*dto.RawUpstream{rawUpstreams[1]}, unresolvedDep)
			assert.NotNil(t, err)
			assert.Equal(t, []*job.Upstream{upstreamB}, result)
		})
	})
}

// ResourceManager is an autogenerated mock type for the ResourceManager type
type ResourceManager struct {
	mock.Mock
}

// GetOptimusUpstreams provides a mock function with given fields: _a0, _a1
func (_m *ResourceManager) GetOptimusUpstreams(_a0 context.Context, _a1 *dto.RawUpstream) ([]*job.Upstream, error) {
	ret := _m.Called(_a0, _a1)

	var r0 []*job.Upstream
	if rf, ok := ret.Get(0).(func(context.Context, *dto.RawUpstream) []*job.Upstream); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*job.Upstream)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *dto.RawUpstream) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
