// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: odpf/optimus/cluster/command.proto

package optimus

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandLog_Type int32

const (
	CommandLog_COMMAND_TYPE_UNKNOWN      CommandLog_Type = 0
	CommandLog_COMMAND_TYPE_NOOP         CommandLog_Type = 1
	CommandLog_COMMAND_TYPE_SCHEDULE_JOB CommandLog_Type = 2
	CommandLog_COMMAND_TYPE_UPDATE_JOB   CommandLog_Type = 3
)

// Enum value maps for CommandLog_Type.
var (
	CommandLog_Type_name = map[int32]string{
		0: "COMMAND_TYPE_UNKNOWN",
		1: "COMMAND_TYPE_NOOP",
		2: "COMMAND_TYPE_SCHEDULE_JOB",
		3: "COMMAND_TYPE_UPDATE_JOB",
	}
	CommandLog_Type_value = map[string]int32{
		"COMMAND_TYPE_UNKNOWN":      0,
		"COMMAND_TYPE_NOOP":         1,
		"COMMAND_TYPE_SCHEDULE_JOB": 2,
		"COMMAND_TYPE_UPDATE_JOB":   3,
	}
)

func (x CommandLog_Type) Enum() *CommandLog_Type {
	p := new(CommandLog_Type)
	*p = x
	return p
}

func (x CommandLog_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandLog_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_odpf_optimus_cluster_command_proto_enumTypes[0].Descriptor()
}

func (CommandLog_Type) Type() protoreflect.EnumType {
	return &file_odpf_optimus_cluster_command_proto_enumTypes[0]
}

func (x CommandLog_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandLog_Type.Descriptor instead.
func (CommandLog_Type) EnumDescriptor() ([]byte, []int) {
	return file_odpf_optimus_cluster_command_proto_rawDescGZIP(), []int{0, 0}
}

type CommandLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    CommandLog_Type `protobuf:"varint,1,opt,name=type,proto3,enum=odpf.optimus.internal.CommandLog_Type" json:"type,omitempty"`
	Payload []byte          `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *CommandLog) Reset() {
	*x = CommandLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_cluster_command_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandLog) ProtoMessage() {}

func (x *CommandLog) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_cluster_command_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandLog.ProtoReflect.Descriptor instead.
func (*CommandLog) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_cluster_command_proto_rawDescGZIP(), []int{0}
}

func (x *CommandLog) GetType() CommandLog_Type {
	if x != nil {
		return x.Type
	}
	return CommandLog_COMMAND_TYPE_UNKNOWN
}

func (x *CommandLog) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type CommandNoop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CommandNoop) Reset() {
	*x = CommandNoop{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_cluster_command_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandNoop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandNoop) ProtoMessage() {}

func (x *CommandNoop) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_cluster_command_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandNoop.ProtoReflect.Descriptor instead.
func (*CommandNoop) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_cluster_command_proto_rawDescGZIP(), []int{1}
}

func (x *CommandNoop) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// CommandScheduleJob will be sent to assign job for execution to a peer
type CommandScheduleJob struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// peer_id is the node name to which this job is assigned to get
	// executed
	PeerId string   `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	RunIds []string `protobuf:"bytes,2,rep,name=run_ids,json=runIds,proto3" json:"run_ids,omitempty"`
}

func (x *CommandScheduleJob) Reset() {
	*x = CommandScheduleJob{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_cluster_command_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandScheduleJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandScheduleJob) ProtoMessage() {}

func (x *CommandScheduleJob) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_cluster_command_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandScheduleJob.ProtoReflect.Descriptor instead.
func (*CommandScheduleJob) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_cluster_command_proto_rawDescGZIP(), []int{2}
}

func (x *CommandScheduleJob) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *CommandScheduleJob) GetRunIds() []string {
	if x != nil {
		return x.RunIds
	}
	return nil
}

// CommandUpdateJob will be sent to update the attributes of job which was
// previously scheduled for execution
type CommandUpdateJob struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PeerId  string                    `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Patches []*CommandUpdateJob_Patch `protobuf:"bytes,2,rep,name=patches,proto3" json:"patches,omitempty"`
}

func (x *CommandUpdateJob) Reset() {
	*x = CommandUpdateJob{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_cluster_command_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandUpdateJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandUpdateJob) ProtoMessage() {}

func (x *CommandUpdateJob) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_cluster_command_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandUpdateJob.ProtoReflect.Descriptor instead.
func (*CommandUpdateJob) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_cluster_command_proto_rawDescGZIP(), []int{3}
}

func (x *CommandUpdateJob) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *CommandUpdateJob) GetPatches() []*CommandUpdateJob_Patch {
	if x != nil {
		return x.Patches
	}
	return nil
}

type CommandUpdateJob_Patch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RunId  string `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *CommandUpdateJob_Patch) Reset() {
	*x = CommandUpdateJob_Patch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_cluster_command_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandUpdateJob_Patch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandUpdateJob_Patch) ProtoMessage() {}

func (x *CommandUpdateJob_Patch) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_cluster_command_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandUpdateJob_Patch.ProtoReflect.Descriptor instead.
func (*CommandUpdateJob_Patch) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_cluster_command_proto_rawDescGZIP(), []int{3, 0}
}

func (x *CommandUpdateJob_Patch) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *CommandUpdateJob_Patch) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_odpf_optimus_cluster_command_proto protoreflect.FileDescriptor

var file_odpf_optimus_cluster_command_proto_rawDesc = []byte{
	0x0a, 0x22, 0x6f, 0x64, 0x70, 0x66, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2f, 0x63,
	0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d,
	0x75, 0x73, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x22, 0xd7, 0x01, 0x0a, 0x0a,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x4c, 0x6f, 0x67, 0x12, 0x3a, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x26, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e,
	0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x4c, 0x6f, 0x67, 0x2e, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x22, 0x73, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x14, 0x43, 0x4f, 0x4d, 0x4d,
	0x41, 0x4e, 0x44, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e,
	0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x43, 0x4f, 0x4d, 0x4d, 0x41, 0x4e, 0x44, 0x5f, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x4e, 0x4f, 0x4f, 0x50, 0x10, 0x01, 0x12, 0x1d, 0x0a, 0x19, 0x43, 0x4f, 0x4d,
	0x4d, 0x41, 0x4e, 0x44, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x43, 0x48, 0x45, 0x44, 0x55,
	0x4c, 0x45, 0x5f, 0x4a, 0x4f, 0x42, 0x10, 0x02, 0x12, 0x1b, 0x0a, 0x17, 0x43, 0x4f, 0x4d, 0x4d,
	0x41, 0x4e, 0x44, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x5f,
	0x4a, 0x4f, 0x42, 0x10, 0x03, 0x22, 0x1d, 0x0a, 0x0b, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x4e, 0x6f, 0x6f, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x46, 0x0a, 0x12, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x53,
	0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x4a, 0x6f, 0x62, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x65,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x65, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x75, 0x6e, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x72, 0x75, 0x6e, 0x49, 0x64, 0x73, 0x22, 0xac, 0x01, 0x0a,
	0x10, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4a, 0x6f,
	0x62, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x70, 0x65, 0x65, 0x72, 0x49, 0x64, 0x12, 0x47, 0x0a, 0x07, 0x70, 0x61,
	0x74, 0x63, 0x68, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x6f, 0x64,
	0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x4a, 0x6f, 0x62, 0x2e, 0x50, 0x61, 0x74, 0x63, 0x68, 0x52, 0x07, 0x70, 0x61, 0x74, 0x63,
	0x68, 0x65, 0x73, 0x1a, 0x36, 0x0a, 0x05, 0x50, 0x61, 0x74, 0x63, 0x68, 0x12, 0x15, 0x0a, 0x06,
	0x72, 0x75, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x75,
	0x6e, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x54, 0x0a, 0x1f, 0x69,
	0x6f, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6e, 0x2e, 0x6f, 0x70,
	0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x42, 0x0f,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x4c, 0x6f, 0x67, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50,
	0x01, 0x5a, 0x1e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x64,
	0x70, 0x66, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6e, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_odpf_optimus_cluster_command_proto_rawDescOnce sync.Once
	file_odpf_optimus_cluster_command_proto_rawDescData = file_odpf_optimus_cluster_command_proto_rawDesc
)

func file_odpf_optimus_cluster_command_proto_rawDescGZIP() []byte {
	file_odpf_optimus_cluster_command_proto_rawDescOnce.Do(func() {
		file_odpf_optimus_cluster_command_proto_rawDescData = protoimpl.X.CompressGZIP(file_odpf_optimus_cluster_command_proto_rawDescData)
	})
	return file_odpf_optimus_cluster_command_proto_rawDescData
}

var file_odpf_optimus_cluster_command_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_odpf_optimus_cluster_command_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_odpf_optimus_cluster_command_proto_goTypes = []interface{}{
	(CommandLog_Type)(0),           // 0: odpf.optimus.internal.CommandLog.Type
	(*CommandLog)(nil),             // 1: odpf.optimus.internal.CommandLog
	(*CommandNoop)(nil),            // 2: odpf.optimus.internal.CommandNoop
	(*CommandScheduleJob)(nil),     // 3: odpf.optimus.internal.CommandScheduleJob
	(*CommandUpdateJob)(nil),       // 4: odpf.optimus.internal.CommandUpdateJob
	(*CommandUpdateJob_Patch)(nil), // 5: odpf.optimus.internal.CommandUpdateJob.Patch
}
var file_odpf_optimus_cluster_command_proto_depIdxs = []int32{
	0, // 0: odpf.optimus.internal.CommandLog.type:type_name -> odpf.optimus.internal.CommandLog.Type
	5, // 1: odpf.optimus.internal.CommandUpdateJob.patches:type_name -> odpf.optimus.internal.CommandUpdateJob.Patch
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_odpf_optimus_cluster_command_proto_init() }
func file_odpf_optimus_cluster_command_proto_init() {
	if File_odpf_optimus_cluster_command_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_odpf_optimus_cluster_command_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_cluster_command_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandNoop); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_cluster_command_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandScheduleJob); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_cluster_command_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandUpdateJob); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_cluster_command_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandUpdateJob_Patch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_odpf_optimus_cluster_command_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_odpf_optimus_cluster_command_proto_goTypes,
		DependencyIndexes: file_odpf_optimus_cluster_command_proto_depIdxs,
		EnumInfos:         file_odpf_optimus_cluster_command_proto_enumTypes,
		MessageInfos:      file_odpf_optimus_cluster_command_proto_msgTypes,
	}.Build()
	File_odpf_optimus_cluster_command_proto = out.File
	file_odpf_optimus_cluster_command_proto_rawDesc = nil
	file_odpf_optimus_cluster_command_proto_goTypes = nil
	file_odpf_optimus_cluster_command_proto_depIdxs = nil
}
