name: build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  verify:
    uses: ./.github/workflows/verify.yml
  publish-latest:
    runs-on: ubuntu-latest
    needs: verify
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19'
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: v1.19
          args: -f .goreleaser.latest.yml --rm-dist --skip-validate
        env:
          GITHUB_TOKEN: ${{ secrets.GO_RELEASER_TOKEN }}

  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Installation
        uses: bahmutov/npm-install@v1
        with:
          install-command: yarn
          working-directory: docs
      - name: Build docs
        working-directory: docs
        run: cd docs && yarn build
      - name: Deploy docs
        env:
          GIT_USER: github-actions[bot]
          GIT_PASS: ${{ secrets.GITHUB_TOKEN }}
          DEPLOYMENT_BRANCH: gh-pages
          CURRENT_BRANCH: main
        working-directory: docs
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          yarn deploy